// কেন্দ্রীয় আইকন ম্যাপ — পুরো অ্যাপে ব্যবহৃত সব UI আইকন এখান থেকে আসে।
// আগে প্রতিটা কম্পোনেন্ট নিজে নিজে emoji ("🏠", "📅" ইত্যাদি) ব্যবহার করত,
// যা OS/browser ভেদে ভিন্ন দেখায় এবং সাইজ/রং থিমের সাথে মেলানো যায় না।
// এখন থেকে কোনো আইকন বদলাতে/যোগ করতে শুধু এই একটা ফাইল সম্পাদনা করলেই হবে।
import {
  Home,
  GraduationCap,
  Calendar,
  Wallet,
  TrendingDown,
  BookOpen,
  FileEdit,
  Megaphone,
  BarChart3,
  Globe,
  Settings,
  Lock,
  Bell,
  Smartphone,
  CreditCard,
  Receipt,
  ShieldCheck,
  Landmark,
  Menu,
  X,
  School,
  FileText,
  Plus,
  AlertTriangle,
  CheckCircle2,
  ClipboardList,
  Printer,
  Pencil,
  Users,
  Utensils,
  Zap,
  Wrench,
  Paperclip,
  Package,
  Sparkles,
  Image,
  Inbox,
  MessageCircle,
  KeyRound,
  Eye,
  Rocket,
  Clock,
  Camera,
  Handshake,
  Trophy,
  ChevronLeft,
  ChevronRight,
  UserRound,
  Palette,
  Phone,
  type LucideIcon,
} from "lucide-react";

export const Icons = {
  dashboard: Home,
  students: GraduationCap,
  attendance: Calendar,
  income: Wallet,
  expenses: TrendingDown,
  hifz: BookOpen,
  results: FileEdit,
  assignments: Megaphone,
  reports: BarChart3,
  website: Globe,
  settings: Settings,
  lock: Lock,
  bell: Bell,
  sms: Smartphone,
  paymentGateway: CreditCard,
  institutionBilling: Receipt,
  auditLogs: ShieldCheck,
  brand: Landmark,
  menu: Menu,
  close: X,
  school: School,
  guardianAttendance: Calendar,
  guardianResults: FileText,
  guardianFeed: Megaphone,
  add: Plus,
  alertTriangle: AlertTriangle,
  checkCircle: CheckCircle2,
  clipboard: ClipboardList,
  printer: Printer,
  pencil: Pencil,
  teacherSalary: Users,
  food: Utensils,
  electricity: Zap,
  maintenance: Wrench,
  stationery: Paperclip,
  otherExpense: Package,
  sparkles: Sparkles,
  gallery: Image,
  inbox: Inbox,
  chat: MessageCircle,
  key: KeyRound,
  eye: Eye,
  rocket: Rocket,
  clock: Clock,
  camera: Camera,
  handshake: Handshake,
  trophy: Trophy,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  attachment: Paperclip,
  childAvatar: UserRound,
  palette: Palette,
  // Reports > কল-লিস্ট ফিচার (docs/CALL_LIST_PLAN.md, Phase 2) — green
  // call button per row.
  phone: Phone,
} satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof Icons;
