// কেন্দ্রীয় আইকন ম্যাপ — পুরো অ্যাপে ব্যবহৃত সব UI আইকন এখান থেকে আসে।
// আগে প্রতিটা কম্পোনেন্ট নিজে নিজে emoji ("🏠", "📅" ইত্যাদি) ব্যবহার করত,
// যা OS/browser ভেদে ভিন্ন দেখায় এবং সাইজ/রং থিমের সাথে মেলানো যায় না।
// এখন থেকে কোনো আইকন বদলাতে/যোগ করতে শুধু এই একটা ফাইল সম্পাদনা করলেই হবে।
import {
  Home,
  GraduationCap,
  Calendar,
  Wallet,
  TrendingDown,
  BookOpen,
  FileEdit,
  Megaphone,
  BarChart3,
  Globe,
  Settings,
  Lock,
  Bell,
  Smartphone,
  CreditCard,
  Receipt,
  ShieldCheck,
  Landmark,
  Menu,
  X,
  School,
  FileText,
  Plus,
  AlertTriangle,
  CheckCircle2,
  ClipboardList,
  Printer,
  Pencil,
  Users,
  Utensils,
  Zap,
  Wrench,
  Paperclip,
  Package,
  Sparkles,
  Image,
  Inbox,
  MessageCircle,
  KeyRound,
  Eye,
  Rocket,
  Clock,
  Camera,
  Handshake,
  Trophy,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  UserRound,
  Palette,
  Phone,
  Fingerprint,
  Usb,
  Tv,
  Send,
  IdCard,
  Layers,
  BookMarked,
  UserCog,
  type LucideIcon,
} from "lucide-react";

export const Icons = {
  dashboard: Home,
  students: GraduationCap,
  attendance: Calendar,
  income: Wallet,
  expenses: TrendingDown,
  hifz: BookOpen,
  results: FileEdit,
  admitCards: IdCard,
  examCoverSheets: ClipboardList,
  // docs/STAFF_ATTENDANCE_PLAN.md, Phase 5/6 — staff registry gets its own
  // icon (UserCog, distinct from `students`/GraduationCap and
  // `teacherSalary`/Users above); staff attendance reuses Calendar, same
  // as guardianAttendance above reusing it for a different nav key.
  staff: UserCog,
  staffAttendance: Calendar,
  assignments: Megaphone,
  reports: BarChart3,
  website: Globe,
  settings: Settings,
  lock: Lock,
  bell: Bell,
  sms: Smartphone,
  paymentGateway: CreditCard,
  institutionBilling: Receipt,
  auditLogs: ShieldCheck,
  brand: Landmark,
  menu: Menu,
  close: X,
  school: School,
  guardianAttendance: Calendar,
  guardianResults: FileText,
  guardianFeed: Megaphone,
  add: Plus,
  alertTriangle: AlertTriangle,
  checkCircle: CheckCircle2,
  clipboard: ClipboardList,
  printer: Printer,
  pencil: Pencil,
  teacherSalary: Users,
  food: Utensils,
  electricity: Zap,
  maintenance: Wrench,
  stationery: Paperclip,
  otherExpense: Package,
  sparkles: Sparkles,
  gallery: Image,
  inbox: Inbox,
  chat: MessageCircle,
  key: KeyRound,
  eye: Eye,
  rocket: Rocket,
  clock: Clock,
  camera: Camera,
  handshake: Handshake,
  trophy: Trophy,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  attachment: Paperclip,
  childAvatar: UserRound,
  palette: Palette,
  // Reports > কল-লিস্ট ফিচার (docs/CALL_LIST_PLAN.md, Phase 2) — green
  // call button per row.
  phone: Phone,
  // Attendance device management (docs/ATTENDANCE_DEVICE_SELFSERVICE_PLAN.md,
  // Phase 1B) — nav item + page header icon.
  fingerprint: Fingerprint,
  // Setup guide steps (docs/ATTENDANCE_DEVICE_SELFSERVICE_PLAN.md, Phase 4A) —
  // "connect the bridge" and "open the kiosk screen" steps.
  bridge: Usb,
  kiosk: Tv,
  // Own-phone/SIM bulk SMS gateway nav item
  // (docs/OWN_SIM_BULK_SMS_GATEWAY_PLAN.md, Phase 6) — distinct from the
  // existing `sms` (paid-reseller wallet) icon since these are two separate
  // nav entries.
  bulkSms: Send,
  // Settings.tsx's class-tree editor (Part 1/2/3) — visually distinguishes
  // a বিভাগ/নেসাব (grouping node) from a জামাত/ক্লাস (leaf, where students
  // actually sit) and from a leaf's own বিষয় (subject) entries.
  classGroup: Layers,
  classLeaf: GraduationCap,
  subjectIcon: BookMarked,
} satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof Icons;
