// AUTO-GENERATED by scripts/sync-roles.js — DO NOT EDIT BY HAND.
// Source of truth: server/src/config/roles.js
// Run `npm run sync:roles` after changing that file.

export const ROLE_PERMISSIONS = {
  "Super Admin": [
    "*"
  ],
  "Admin": [
    "dashboard",
    "students",
    "attendance",
    "income",
    "expenses",
    "hifz",
    "reports",
    "settings",
    "website",
    "websiteGallery",
    "websiteNotices",
    "results"
  ],
  "Accountant": [
    "dashboard",
    "income",
    "expenses",
    "reports"
  ],
  "Teacher": [
    "attendance",
    "hifz",
    "results"
  ],
  "Hostel Manager": [
    "dashboard",
    "students",
    "attendance"
  ]
} as const;

export const ROUTE_PERMISSION = {
  "/api/dashboard": "dashboard",
  "/api/delete-requests": "dashboard",
  "/api/students": "students",
  "/api/attendance": "attendance",
  "/api/payments": "income",
  "/api/income": "income",
  "/api/expenses": "expenses",
  "/api/hifz": "hifz",
  "/api/results": "results",
  "/api/settings": "settings",
  "/api/users": "settings",
  "/api/backup": "settings",
  "/api/reports": "reports",
  "/api/audit-logs": "settings",
  "/api/site-content": [
    "website",
    "websiteGallery",
    "websiteNotices"
  ],
  "/api/admissions": "website"
} as const;
