-- ============================================================================
-- Registry schema (Part 1 / 6 — Central Registry Database)
-- ============================================================================
-- This is the master/control-plane schema. It is completely separate from
-- every tenant's data (students, payments, users, etc). It only knows
-- "which institutions exist, what are they called, which DB schema holds
-- their data, and are they allowed to log in right now".
--
-- All statements are idempotent (safe to run again on every boot), matching
-- the existing convention in supabase_schema.sql.
-- ============================================================================

create schema if not exists registry;

-- One row per madrasah/institution ("tenant").
create table if not exists registry.institutions (
  id integer generated by default as identity primary key,
  name text not null,

  -- Short, URL/subdomain-safe identifier, e.g. "abc" -> abc.yourapp.com
  -- Lowercase letters, digits, hyphens only; enforced in registryDb.js as well.
  code text not null,

  -- Actual Postgres schema name that holds this institution's tables,
  -- e.g. "tenant_abc". Kept separate from `code` because Postgres schema
  -- identifiers can't contain hyphens, while subdomains often do.
  schema_name text not null,

  -- trial   -> newly created, within free trial window
  -- active  -> paid/current, full access
  -- suspended -> access blocked (non-payment, manual hold, etc.)
  -- cancelled -> permanently closed, data retained for grace period
  status text not null default 'trial',

  plan text not null default 'basic',

  contact_name text,
  contact_email text,
  contact_phone text,

  trial_ends_at timestamptz,
  subscription_ends_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists institutions_code_unique
  on registry.institutions (lower(code));

create unique index if not exists institutions_schema_name_unique
  on registry.institutions (schema_name);

create index if not exists institutions_status_idx
  on registry.institutions (status);

-- Small global key/value config store for the platform as a whole (not
-- per-institution) — e.g. "how many days of trial does a brand-new
-- self-signup account get". Kept as generic key/value rather than one
-- column per setting so future settings don't each need their own
-- migration; registryDb.js exposes typed getters/setters on top of this.
create table if not exists registry.platform_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

alter table registry.institutions
  add column if not exists status text not null default 'trial';

-- Optional custom domain (e.g. "school.theirdomain.com" or
-- "theirdomain.com") an institution points at this app instead of using
-- the platform's own subdomain. NULL means "no custom domain configured,
-- use the subdomain as usual". Verification (DNS actually pointing here)
-- happens at the hosting layer (Vercel/Render "Add Domain"); this column is
-- just what tenantResolve.js matches the request Host header against.
alter table registry.institutions
  add column if not exists custom_domain text;

create unique index if not exists institutions_custom_domain_unique
  on registry.institutions (lower(custom_domain))
  where custom_domain is not null;

-- Guard against typos / bad data from the provisioning script.
alter table registry.institutions drop constraint if exists institutions_status_check;
alter table registry.institutions
  add constraint institutions_status_check
  check (status in ('trial', 'active', 'suspended', 'cancelled'));

-- Platform-level operators (you / your team), distinct from any single
-- institution's "Super Admin" user. These log in to the future Super-Admin
-- panel (Part 5), not to any madrasah's own dashboard.
create table if not exists registry.platform_admins (
  id integer generated by default as identity primary key,
  name text not null,
  email text not null,
  "passwordHash" text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists platform_admins_email_unique
  on registry.platform_admins (lower(email));

-- Phase 6 — billing model scaffolding. The user wants two supported
-- pricing systems (per-student and flat monthly) but hasn't decided the
-- actual numbers yet, so both columns are nullable: NULL means "not priced
-- yet" (e.g. demo/trial institutions), to be set per-institution later from
-- the Super-Admin panel (routes/platform.js) once real pricing is decided.
-- Nothing reads these columns to gate access yet — server/src/config/
-- planFeatures.js (plan tier) is what actually gates features; these two
-- columns are for billing/invoicing bookkeeping only.
alter table registry.institutions
  add column if not exists billing_model text;

alter table registry.institutions drop constraint if exists institutions_billing_model_check;
alter table registry.institutions
  add constraint institutions_billing_model_check
  check (billing_model is null or billing_model in ('student', 'flat'));

alter table registry.institutions
  add column if not exists price_amount numeric(12, 2);

-- Multiple platform-level operator accounts (Part 5.1): every existing row
-- predates this column and represents an account that already had full
-- control of the panel, so the default keeps that behavior unchanged for
-- them ('super_admin'). New accounts created afterwards specify their own
-- role explicitly (see registryDb.createPlatformAdmin).
--   super_admin -> everything, including managing other platform admins
--   admin       -> full institution management, cannot manage other admins
--   manager     -> read-only + routine actions (status/subscription/payments),
--                  cannot delete institutions, run migrations, or manage admins
alter table registry.platform_admins
  add column if not exists role text not null default 'super_admin';

alter table registry.platform_admins drop constraint if exists platform_admins_role_check;
alter table registry.platform_admins
  add constraint platform_admins_role_check
  check (role in ('super_admin', 'admin', 'manager'));

-- Lightweight audit trail for platform-level actions (create/suspend/etc).
-- Kept separate from the existing tenant-level audit_logs table.
create table if not exists registry.audit_logs (
  id integer generated by default as identity primary key,
  institution_id integer references registry.institutions(id) on delete set null,
  actor_email text,
  action text not null,
  detail jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists registry_audit_logs_institution_idx
  on registry.audit_logs (institution_id);

-- ============================================================================
-- Part 6 / 6 — Billing (manual payment ledger)
-- ============================================================================
-- One row per recorded subscription payment. This is a LEDGER, not a live
-- payment-gateway integration: bKash/Nagad/SSLCommerz in Bangladesh
-- typically require a registered merchant account and a public HTTPS
-- callback URL, neither of which exist yet for this project, so Part 6
-- records payments that you (the platform operator) confirm by hand — e.g.
-- after checking a bKash SMS/statement — via the Super-Admin panel or CLI.
-- The `reference` column exists specifically to hold that gateway's own
-- transaction ID for later reconciliation. A real gateway can be wired in
-- later by having its webhook call registryDb.recordPayment() with the same
-- shape, so nothing here needs to change when that happens.
create table if not exists registry.payments (
  id integer generated by default as identity primary key,
  institution_id integer not null references registry.institutions(id) on delete cascade,
  amount numeric(12, 2) not null,
  currency text not null default 'BDT',
  method text not null default 'manual',
  reference text,
  period_days integer not null default 30,
  covers_until timestamptz not null,
  recorded_by text,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists registry_payments_institution_idx
  on registry.payments (institution_id);

-- ============================================================================
-- Platform self-service billing (ad-hoc — not a BUSINESS_READINESS_ROADMAP.md
-- Phase; direction is the reverse of Phase 8E/8F: institution -> platform,
-- not guardian -> institution). See docs/CURRENT_TASK.md for the full task
-- writeup.
-- ============================================================================

-- The platform operator's OWN bKash merchant/agent account — exactly one
-- row, same shape as supabase_schema.sql's institution_payment_gateways,
-- but living in `registry` because it belongs to the platform, not any one
-- institution. Institutions pay their monthly bill through THIS gateway
-- (routes/institutionBilling.js), separate from their own connected
-- gateway (institution_payment_gateways) which they use to collect fees
-- from guardians. Encrypted with the same GATEWAY_CREDENTIAL_KEY as
-- institution_payment_gateways (lib/gatewayCredentialCrypto.js) — a leak of
-- one doesn't expose the other, they're just sharing the same cipher.
create table if not exists registry.platform_gateway (
  id integer generated by default as identity primary key,
  provider text not null default 'bkash',
  "appKeyEnc" text,
  "appSecretEnc" text,
  "usernameEnc" text,
  "passwordEnc" text,
  connected boolean not null default false,
  "lastCheckedAt" timestamptz,
  "lastError" text,
  updated_at timestamptz not null default now()
);

-- registry-schema counterpart of supabase_schema.sql's
-- bkash_payment_intents, for the platform-billing direction: one row per
-- checkout attempt an institution starts to pay ITS OWN subscription bill.
-- institution_id (not guardianId/studentId) identifies who's paying.
-- Execute finalizes based only on bKash's own execute-payment response
-- (never the redirect query string — same reasoning as bkash_payment_intents),
-- then calls registryDb.recordPayment(institution_id, ...) exactly once —
-- status='completed' makes a second execute call for the same paymentID a
-- no-op instead of re-crediting the subscription.
create table if not exists registry.platform_payment_intents (
  id integer generated by default as identity primary key,
  institution_id integer not null references registry.institutions(id) on delete cascade,
  "paymentId" text,
  amount integer not null,
  "periodDays" integer not null default 30,
  status text not null default 'initiated',
  "bkashTrxId" text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists platform_payment_intents_institution_idx
  on registry.platform_payment_intents (institution_id);

-- ============================================================================
-- Global device registry (ad-hoc —
-- docs/ATTENDANCE_DEVICE_CENTRALIZED_INGESTION_PLAN.md, Phase 1)
-- ============================================================================
-- A bridge-free Push/ADMS attendance device (see the plan doc's section 3.2)
-- sends its raw device_id straight to the server with no subdomain/Host
-- header to resolve the tenant from — so this table is the one place that
-- maps a device_id back to which institution/schema owns it. device_id is
-- the primary key here, so it's enforced GLOBALLY unique across every
-- institution (stricter than the existing per-tenant
-- attendance_devices_device_id_unique index).
--
-- deviceId/secretKey ownership stays tenant-side (attendance_devices is
-- still the source of truth for name/location/active) — this is only a
-- cross-tenant lookup index, kept in sync by routes/attendanceDevices.js
-- whenever a device is created/updated/secret-regenerated. Single-tenant
-- deployments (MULTI_TENANT_MODE off, no institution in tenantContext)
-- never write here.
create table if not exists registry.device_registry (
  device_id text primary key,
  institution_id integer not null references registry.institutions(id) on delete cascade,
  schema_name text not null,
  secret_or_comm_key text not null,
  -- 'push_adms' (server understands the protocol directly, no local
  -- program needed), 'key_reader' (USB keyboard-emulation, types straight
  -- into the kiosk page — also bridge-free), 'pull_sdk' (device is
  -- passive, needs hardware-bridge/ or a brand-cloud adapter, see the
  -- plan doc's section 3.3/3.4).
  protocol text not null default 'push_adms',
  brand text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists device_registry_institution_idx
  on registry.device_registry (institution_id);

-- ============================================================================
-- Institution type (docs/GENERAL_MODE_PLAN.md, Phase 1)
-- ============================================================================
-- Distinguishes a madrasah tenant from a "general" tenant (school / college /
-- coaching center — plan doc §5 open question 1 decided these all share the
-- single 'general' value rather than separate enum values, so classTree's
-- default seed and the hifzTracking feature gate can branch on this one
-- column instead of a growing list of institution kinds).
--
-- Default 'madrasah' (plan doc §5 open question 2) keeps every existing
-- tenant's behavior unchanged — nothing reads this column yet, so this
-- migration alone has no visible effect. Later phases will start reading it:
-- Phase 2 (signup flow + classTree default seed), Phase 3 (hifzTracking gate).
--
-- Single-tenant deployments (MULTI_TENANT_MODE=false, no registry.institutions
-- row at all) have no row for this column to live on — Phase 2 will need its
-- own fallback for that case (likely a settings-table key, same pattern as
-- classOptionsTree) when it starts actually reading institution_type.
alter table registry.institutions
  add column if not exists institution_type text not null default 'madrasah';

alter table registry.institutions drop constraint if exists institutions_institution_type_check;
alter table registry.institutions
  add constraint institutions_institution_type_check
  check (institution_type in ('madrasah', 'general'));
