-- ============================================================================
-- Registry schema (Part 1 / 6 — Central Registry Database)
-- ============================================================================
-- This is the master/control-plane schema. It is completely separate from
-- every tenant's data (students, payments, users, etc). It only knows
-- "which institutions exist, what are they called, which DB schema holds
-- their data, and are they allowed to log in right now".
--
-- All statements are idempotent (safe to run again on every boot), matching
-- the existing convention in supabase_schema.sql.
-- ============================================================================

create schema if not exists registry;

-- One row per madrasah/institution ("tenant").
create table if not exists registry.institutions (
  id integer generated by default as identity primary key,
  name text not null,

  -- Short, URL/subdomain-safe identifier, e.g. "abc" -> abc.yourapp.com
  -- Lowercase letters, digits, hyphens only; enforced in registryDb.js as well.
  code text not null,

  -- Actual Postgres schema name that holds this institution's tables,
  -- e.g. "tenant_abc". Kept separate from `code` because Postgres schema
  -- identifiers can't contain hyphens, while subdomains often do.
  schema_name text not null,

  -- trial   -> newly created, within free trial window
  -- active  -> paid/current, full access
  -- suspended -> access blocked (non-payment, manual hold, etc.)
  -- cancelled -> permanently closed, data retained for grace period
  status text not null default 'trial',

  plan text not null default 'basic',

  contact_name text,
  contact_email text,
  contact_phone text,

  trial_ends_at timestamptz,
  subscription_ends_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists institutions_code_unique
  on registry.institutions (lower(code));

create unique index if not exists institutions_schema_name_unique
  on registry.institutions (schema_name);

create index if not exists institutions_status_idx
  on registry.institutions (status);

alter table registry.institutions
  add column if not exists status text not null default 'trial';

-- Guard against typos / bad data from the provisioning script.
alter table registry.institutions drop constraint if exists institutions_status_check;
alter table registry.institutions
  add constraint institutions_status_check
  check (status in ('trial', 'active', 'suspended', 'cancelled'));

-- Platform-level operators (you / your team), distinct from any single
-- institution's "Super Admin" user. These log in to the future Super-Admin
-- panel (Part 5), not to any madrasah's own dashboard.
create table if not exists registry.platform_admins (
  id integer generated by default as identity primary key,
  name text not null,
  email text not null,
  "passwordHash" text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists platform_admins_email_unique
  on registry.platform_admins (lower(email));

-- Lightweight audit trail for platform-level actions (create/suspend/etc).
-- Kept separate from the existing tenant-level audit_logs table.
create table if not exists registry.audit_logs (
  id integer generated by default as identity primary key,
  institution_id integer references registry.institutions(id) on delete set null,
  actor_email text,
  action text not null,
  detail jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists registry_audit_logs_institution_idx
  on registry.audit_logs (institution_id);
