create table if not exists students (
  id integer generated by default as identity primary key,
  name text not null,
  "nameEn" text default '',
  roll text not null,
  class text default '',
  dept text default 'হিফজ',
  type text default 'আবাসিক',
  fee integer default 1500,
  due integer default 0,
  phone text default '',
  blood text default 'O+',
  para integer default 0,
  status text default 'সক্রিয়'
);

alter table students add column if not exists "admissionNumber" text;
alter table students add column if not exists "admissionDate" text;
alter table students add column if not exists "academicYear" text;
alter table students add column if not exists session text;
alter table students add column if not exists section text;
alter table students add column if not exists "dateOfBirth" text;
alter table students add column if not exists "birthRegistrationNumber" text;
alter table students add column if not exists gender text;
alter table students add column if not exists religion text;
alter table students add column if not exists "studentPhoto" text;
alter table students add column if not exists "fatherName" text;
alter table students add column if not exists "fatherMobile" text;
alter table students add column if not exists "fatherOccupation" text;
alter table students add column if not exists "motherName" text;
alter table students add column if not exists "motherMobile" text;
alter table students add column if not exists "motherOccupation" text;
alter table students add column if not exists "guardianName" text;
alter table students add column if not exists "guardianRelationship" text;
alter table students add column if not exists "guardianMobile" text;
alter table students add column if not exists "presentAddress" text;
alter table students add column if not exists "permanentAddress" text;
alter table students add column if not exists district text;
alter table students add column if not exists upazila text;
alter table students add column if not exists "postOffice" text;
alter table students add column if not exists village text;
alter table students add column if not exists "previousInstitution" text;
alter table students add column if not exists "previousClass" text;
alter table students add column if not exists "admissionFee" integer default 0;
alter table students add column if not exists discount integer default 0;
alter table students add column if not exists documents jsonb default '{}'::jsonb;

create unique index if not exists students_admission_number_unique
on students ("admissionNumber")
where "admissionNumber" is not null and "admissionNumber" <> '';

create unique index if not exists students_birth_registration_unique
on students ("birthRegistrationNumber")
where "birthRegistrationNumber" is not null and "birthRegistrationNumber" <> '';

create table if not exists attendance (
  id integer generated by default as identity primary key,
  "studentId" integer not null references students(id) on delete cascade,
  date text not null,
  status text not null,
  unique ("studentId", date)
);

create table if not exists payments (
  id integer generated by default as identity primary key,
  "studentId" integer references students(id) on delete set null,
  student text not null,
  roll text not null,
  amount integer not null,
  date text not null,
  receipt text not null,
  method text default 'Cash',
  status text default 'Completed'
);

create unique index if not exists payments_receipt_unique on payments (receipt);

-- Offline-first Phase 5 (fee collection): when a payment syncs and the
-- student's due is already 0 (most likely two staff collected the same
-- fee while both were offline), the row is kept with status = 'Flagged'
-- and this reason instead of being silently double-booked — see
-- server/src/routes/payments.js's isConflict branch and the
-- POST /:id/resolve-flag endpoint that clears it.
alter table payments add column if not exists "flagReason" text;

-- BUSINESS_READINESS_ROADMAP.md Phase 1 (2026-08-05): studentId used to be
-- "not null ... on delete cascade", so deleting a student silently deleted
-- all of their payment/receipt history too — a real problem for a
-- financial/audit record (income.studentId had the same issue and was
-- already fixed to "on delete set null", see the income table above; this
-- brings payments in line with it). student/roll are already stored as a
-- denormalized snapshot on this table (see the comment above the results
-- table), so a receipt still shows the right name/roll even after
-- studentId goes null. This block is a no-op on a brand-new database
-- (matches the create table statement above already) and only does real
-- work on a database created before this fix.
alter table payments alter column "studentId" drop not null;
alter table payments drop constraint if exists "payments_studentId_fkey";
alter table payments add constraint "payments_studentId_fkey"
  foreign key ("studentId") references students(id) on delete set null;

create table if not exists income (
  id integer generated by default as identity primary key,
  category text not null,
  amount integer not null,
  date text not null,
  note text default '',
  method text default 'Cash',
  receipt text not null,
  "studentId" integer references students(id) on delete set null,
  status text default 'Completed'
);

create unique index if not exists income_receipt_unique on income (receipt);

create table if not exists expenses (
  id integer generated by default as identity primary key,
  cat text not null,
  amount integer not null,
  date text not null,
  note text default ''
);

create table if not exists hifz_logs (
  id integer generated by default as identity primary key,
  "studentId" integer not null references students(id) on delete cascade,
  date text not null,
  sabaq text default ''
);

-- Exam results. "class"/"roll"/"studentName" are stored as a snapshot at
-- save time (same denormalization pattern as payments.student/payments.roll
-- above) so a result stays correct even if a student later changes class or
-- is edited. "published" gates public visibility: staff can enter and
-- correct marks freely, and results only become visible on the public
-- Result Lookup page once explicitly published.
create table if not exists results (
  id integer generated by default as identity primary key,
  "studentId" integer not null references students(id) on delete cascade,
  "examName" text not null,
  year text not null,
  class text not null,
  roll text not null,
  "studentName" text not null,
  subjects jsonb not null default '[]',
  "totalMarks" integer default 0,
  "obtainedMarks" integer default 0,
  gpa text default '',
  grade text default '',
  published integer default 0,
  "updatedAt" timestamptz default now(),
  unique ("studentId", "examName", year)
);

create index if not exists results_lookup_idx on results (class, roll, "examName", published);

create table if not exists settings (
  key text primary key,
  value text not null
);

create table if not exists users (
  id integer generated by default as identity primary key,
  name text not null,
  role text not null default 'Teacher',
  email text unique,
  "passwordHash" text,
  "isProtected" integer default 0
);

-- Account-level brute-force lockout (task 1.2). Added via ALTER because the
-- CREATE TABLE above is a no-op once the table already exists on deployed DBs.
alter table users add column if not exists "failedLoginAttempts" integer not null default 0;
alter table users add column if not exists "lockedUntil" timestamptz;

create table if not exists password_resets (
  id integer generated by default as identity primary key,
  "userId" integer not null references users(id) on delete cascade,
  token text not null unique,
  "expiresAt" text not null
);

create table if not exists delete_requests (
  id integer generated by default as identity primary key,
  "entityType" text not null,
  "entityId" integer not null,
  label text not null,
  amount integer default 0,
  "requestedBy" integer,
  "requestedByName" text default '',
  status text not null default 'pending',
  "createdAt" text not null,
  "resolvedAt" text,
  "resolvedBy" integer,
  payload text default ''
);

create unique index if not exists delete_requests_pending_unique
on delete_requests ("entityType", "entityId", status)
where status = 'pending';

create table if not exists receipt_counters (
  "key" text primary key,
  value bigint not null default 0
);

-- Offline-first foundation (Phase 0): lets the idempotency middleware
-- (server/src/middleware/idempotency.js) recognize a retried mutation —
-- e.g. a payment or admission submitted while offline, queued client-side,
-- and resent once the connection returns — as the SAME request rather than
-- creating a duplicate. clientRequestId is generated in the browser (see
-- client/src/lib/api.ts) and sent as the X-Client-Request-Id header.
create table if not exists sync_requests (
  "clientRequestId" text primary key,
  route text not null,
  "statusCode" integer not null,
  response jsonb default '{}'::jsonb,
  "createdAt" text not null
);

create table if not exists audit_logs (
  id integer generated by default as identity primary key,
  "action" text not null,
  "actorId" integer,
  "actorName" text default '',
  "actorRole" text default '',
  "entityType" text default '',
  "entityId" integer,
  label text default '',
  details text default '',
  "createdAt" text not null
);

create index if not exists audit_logs_created_at_idx on audit_logs ("createdAt" desc);

create table if not exists backup_restore_events (
  id integer generated by default as identity primary key,
  event text not null,
  status text not null,
  "requestedBy" integer,
  "requestedByName" text default '',
  "backupVersion" integer,
  "backupFormat" text default '',
  report jsonb default '{}'::jsonb,
  error text default '',
  "createdAt" text not null
);

-- Public "ভর্তি" (admission) form submissions from the marketing site.
-- Distinct from `students`: these are unverified inbound inquiries a staff
-- member reviews before a real student record is created.
create table if not exists admissions (
  id integer generated by default as identity primary key,
  "studentName" text not null,
  "studentNameEn" text default '',
  "dateOfBirth" text default '',
  gender text default '',
  "className" text not null,
  "guardianName" text not null,
  "guardianPhone" text not null,
  "presentAddress" text default '',
  "previousInstitution" text default '',
  note text default '',
  status text not null default 'Pending',
  "createdAt" text not null
);

create index if not exists admissions_created_at_idx on admissions ("createdAt" desc);

-- In-app notification center. A row is either targeted at specific roles
-- (targetRoles, e.g. new admission -> ["Admin","Super Admin"]) or at one
-- specific user (targetUserId, e.g. "your delete request was approved").
-- Read state is tracked per-user in notification_reads rather than a single
-- boolean on this table, since the same role-targeted notification can be
-- read by one Admin and still unread for another.
create table if not exists notifications (
  id integer generated by default as identity primary key,
  type text not null,
  title text not null,
  body text default '',
  "entityType" text default '',
  "entityId" integer,
  link text default '',
  "targetRoles" text[] not null default '{}',
  "targetUserId" integer references users(id) on delete cascade,
  "createdAt" text not null
);

create index if not exists notifications_created_at_idx on notifications ("createdAt" desc);

create table if not exists notification_reads (
  "notificationId" integer not null references notifications(id) on delete cascade,
  "userId" integer not null references users(id) on delete cascade,
  "readAt" text not null,
  primary key ("notificationId", "userId")
);

-- ============================================================
-- Guardian Portal + Teacher Class-Scoping — Step 1 (DB schema)
-- ============================================================
-- Separate login identity from `users` (staff). A guardian account is
-- created via self-signup (4-field match: name/roll/class/guardianMobile
-- against an existing students row — see the signup endpoint added in
-- Step 2) and starts as "pending" or "active" depending on match strength,
-- same tri-state pattern as delete_requests.status above.
create table if not exists guardian_accounts (
  id integer generated by default as identity primary key,
  name text not null,
  mobile text,
  email text,
  "passwordHash" text not null,
  status text not null default 'pending',
  "failedLoginAttempts" integer not null default 0,
  "lockedUntil" timestamptz,
  "createdAt" text not null
);

-- A guardian can be blank on whichever contact field they didn't sign up
-- with, so uniqueness is partial (mirrors students_admission_number_unique
-- above) rather than a plain unique column constraint.
create unique index if not exists guardian_accounts_mobile_unique
on guardian_accounts (mobile)
where mobile is not null and mobile <> '';

create unique index if not exists guardian_accounts_email_unique
on guardian_accounts (email)
where email is not null and email <> '';

-- Many-to-many: one guardian can be linked to more than one child ("আরেকটি
-- সন্তান যুক্ত করুন" in Step 2), and — rare but possible with blended
-- families — a student could in principle have more than one linked
-- guardian account, so this is a junction table rather than a single FK
-- column on either side.
create table if not exists guardian_students (
  "guardianId" integer not null references guardian_accounts(id) on delete cascade,
  "studentId" integer not null references students(id) on delete cascade,
  "createdAt" text not null,
  primary key ("guardianId", "studentId")
);

create index if not exists guardian_students_student_idx on guardian_students ("studentId");

-- Step 2 Part 2: a later child-link request may need Admin review even when
-- the guardian account itself is already active. Existing links (including
-- links created by Step 2 Part 1) remain active by default.
alter table guardian_students add column if not exists status text not null default 'active';
alter table guardian_students add column if not exists "matchCount" integer;
alter table guardian_students add column if not exists "reviewedAt" text;
alter table guardian_students add column if not exists "reviewedBy" integer references users(id) on delete set null;

create index if not exists guardian_students_status_idx on guardian_students (status);

-- Which classes a Teacher may see/act on. Only Super Admin/Admin write this
-- (via /api/users, permission "settings" — Step 3), a Teacher never edits
-- their own assignments. `class` stores the same English slug value as
-- students.class (see lib/classOptions.js), not a foreign key since the
-- class/jamaat list itself lives in settings.classOptions (JSON), not its
-- own table.
create table if not exists teacher_class_assignments (
  id integer generated by default as identity primary key,
  "userId" integer not null references users(id) on delete cascade,
  class text not null,
  "createdAt" text not null,
  unique ("userId", class)
);

create index if not exists teacher_class_assignments_user_idx on teacher_class_assignments ("userId");

-- Class-broadcast model (Step 4): a Teacher posts once per class instead of
-- once per student; the guardian feed is produced by joining this table
-- against guardian_students/students at read time, so there is no
-- per-guardian fan-out row to keep in sync.
create table if not exists class_posts (
  id integer generated by default as identity primary key,
  type text not null,
  class text not null,
  "teacherId" integer references users(id) on delete set null,
  title text not null,
  body text default '',
  attachments jsonb default '[]'::jsonb,
  "createdAt" text not null
);

create index if not exists class_posts_class_created_idx on class_posts (class, "createdAt" desc);

-- Step 4: per-guardian read-tracking for the class-broadcast feed. The plan
-- called for reusing the existing notifications/notification_reads tables
-- for this, but notification_reads."userId" (and notifications."targetUserId")
-- are hard FK'd to users(id) — the STAFF table — so a guardian_accounts.id
-- can never be stored there safely (either the FK insert fails outright, or
-- if the id ranges happened to overlap it would silently point at the
-- wrong staff member). This is the guardian-side equivalent instead: same
-- shape as notification_reads, but keyed to guardian_accounts and
-- class_posts. A missing row = unread, same "absence means unread" contract
-- notification_reads already uses for staff.
create table if not exists class_post_reads (
  "postId" integer not null references class_posts(id) on delete cascade,
  "guardianId" integer not null references guardian_accounts(id) on delete cascade,
  "readAt" text not null,
  primary key ("postId", "guardianId")
);

create index if not exists class_post_reads_guardian_idx on class_post_reads ("guardianId");

-- ============================================================
-- Guardian Reminder Messenger (ad-hoc — see docs/CURRENT_TASK.md, not a
-- BUSINESS_READINESS_ROADMAP phase)
-- ============================================================
-- Admin-authored reminder definitions. Turned into actual per-guardian
-- guardian_messages rows by lib/guardianReminders.js's dispatchDueReminders
-- — scheduled the same setInterval way billing.js's expiry scan is
-- (AGENTS.md Rule 5: no new cron npm dependency), plus a manual
-- POST /api/guardian-reminders/dispatch button for on-demand sends.
-- Deliberately NOT reusing class_posts: a reminder needs its own targeting
-- (all/class/single-student) and schedule (once/daily/specificDate)
-- columns class_posts has no reason to carry.
create table if not exists guardian_reminders (
  id integer generated by default as identity primary key,
  title text not null,
  body text not null default '',
  "targetType" text not null default 'all', -- 'all' | 'class' | 'student'
  "targetClass" text,
  "targetStudentId" integer references students(id) on delete cascade,
  "scheduleType" text not null default 'once', -- 'once' | 'daily' | 'specificDate'
  "scheduleDate" text, -- 'YYYY-MM-DD'; required for 'specificDate', unused otherwise
  active boolean not null default true,
  "createdBy" integer references users(id) on delete set null,
  "createdAt" text not null,
  "lastSentAt" text
);

create index if not exists guardian_reminders_active_idx on guardian_reminders (active);

-- One row per guardian per dispatch — a 'daily' reminder targeting 200
-- guardians produces 200 rows every day it fires. Unlike class_posts (a
-- join-at-read-time feed), a reminder's whole point is per-guardian
-- delivery + per-guardian read state, so fan-out at write time is the
-- right tradeoff here.
create table if not exists guardian_messages (
  id integer generated by default as identity primary key,
  "reminderId" integer references guardian_reminders(id) on delete set null,
  "guardianId" integer not null references guardian_accounts(id) on delete cascade,
  title text not null,
  body text not null default '',
  "createdAt" text not null,
  "readAt" text
);

create index if not exists guardian_messages_guardian_idx on guardian_messages ("guardianId");
create index if not exists guardian_messages_reminder_idx on guardian_messages ("reminderId", "createdAt");

-- ============================================================
-- Guardian Push Notifications (docs/PUSH_NOTIFICATION_PLAN.md — Phase 1)
-- ============================================================
-- One row per subscribed browser/device per guardian (a guardian logged in
-- on both their phone and a desktop browser gets two rows, both receive a
-- push). "endpoint" is the browser's own unique per-subscription push URL
-- — used as the natural upsert key so re-subscribing the same
-- browser/device (e.g. after clearing site data) updates the existing row
-- instead of accumulating duplicates. "p256dh"/"auth" are the
-- browser-generated encryption keys the Web Push spec requires to encrypt
-- the payload — meaningless without the matching VAPID private key
-- (server/src/lib/guardianPush.js, Phase 2), so no additional encryption
-- is needed on this table itself. A subscription is deleted outright (not
-- soft-deleted/deactivated) either when the guardian explicitly
-- unsubscribes or when a push attempt gets back 404/410 Gone from the
-- push service (guardianPush.js's own cleanup, not here) — there is no
-- reason to keep a dead subscription row around.
create table if not exists guardian_push_subscriptions (
  id integer generated by default as identity primary key,
  "guardianId" integer not null references guardian_accounts(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  "userAgent" text,
  "createdAt" text not null
);

create index if not exists guardian_push_subscriptions_guardian_idx on guardian_push_subscriptions ("guardianId");

-- ============================================================
-- BUSINESS_READINESS_ROADMAP.md Phase 8A — SMS wallet + ledger
-- ============================================================
-- Schema-per-tenant means this table lives inside one institution's own
-- schema (search_path-scoped, same as every other table above) — so unlike
-- a shared multi-tenant table, it does NOT need an "institutionId" column
-- to separate rows between institutions. Each tenant schema, and the
-- single-tenant `public` schema, gets exactly one wallet row: application
-- code (smsSender.js, Phase 8B) always reads/updates that one row rather
-- than looking one up by institution. The row itself is inserted once, at
-- provisioning time (tenantProvision.js for a new tenant; db.js's initDb()
-- for a single-tenant deployment) — this CREATE TABLE only defines the
-- shape, same convention as `settings` (a table this file never seeds
-- rows into either).
create table if not exists sms_wallets (
  id integer generated by default as identity primary key,
  balance_taka numeric(12,2) not null default 0,
  "updatedAt" timestamptz not null default now()
);

-- Ledger of every wallet change (type: 'topup' | 'deduct'). smsCount is
-- null for a topup row (money added, no SMS sent yet) and set for a deduct
-- row (how many SMS that deduction paid for). reference is free text —
-- e.g. a manual top-up's bKash Trx ID (8D), or the SMS provider's own
-- message/batch id (8B) — kept as a string since the two sources have
-- unrelated id formats. createdAt is text (ISO string), matching every
-- other ledger/log table in this file (audit_logs, notifications,
-- admissions) rather than the timestamptz style used for point-in-time
-- fields like sms_wallets."updatedAt" above.
create table if not exists sms_transactions (
  id integer generated by default as identity primary key,
  type text not null,
  "amountTaka" numeric(12,2) not null,
  "smsCount" integer,
  reference text default '',
  "createdAt" text not null
);

-- BUSINESS_READINESS_ROADMAP.md Phase 8D — manual top-up requests. An
-- institution-admin submits a bKash Trx ID (type='topup', status='pending'
-- row, balance NOT touched yet); a platform Super-Admin checks the real
-- bKash inbox and approves/rejects from the platform panel
-- (routes/platform.js, tenant-scoped via migrateTenants.withTenantSchema).
-- Only approval credits sms_wallets.balance_taka. Every row inserted
-- before this phase (Phase 8B's deduct rows) has no explicit status, so
-- the default keeps them correctly classified as already-settled/
-- "confirmed" rather than retroactively looking "pending".
alter table sms_transactions add column if not exists "status" text not null default 'confirmed';

create index if not exists sms_transactions_created_at_idx on sms_transactions ("createdAt" desc);

-- ============================================================
-- BUSINESS_READINESS_ROADMAP.md Phase 8E — bKash self-connect
-- ============================================================
-- One row per institution's own bKash agent/merchant credentials
-- (Bring-Your-Own-Account — see roadmap Phase 8 intro). Schema-per-tenant
-- means this table lives inside one institution's own schema, same as
-- sms_wallets above, so it needs no institutionId column either — at most
-- one row ever exists here, upserted by routes/paymentGateway.js.
-- Credentials are NEVER stored in plaintext: appKey/appSecret/username/
-- password are each encrypted with lib/gatewayCredentialCrypto.js
-- (AES-256-GCM, same algorithm as lib/backupEncryption.js but for short
-- strings instead of files, keyed by the separate GATEWAY_CREDENTIAL_KEY
-- env var so a leaked backup-encryption key alone can't decrypt these).
-- "connected" only flips true after a live grant-token call against
-- bKash's API actually succeeds (see bkashGateway.js) — submitting the
-- form alone does not set it.
create table if not exists institution_payment_gateways (
  id integer generated by default as identity primary key,
  provider text not null default 'bkash',
  "appKeyEnc" text,
  "appSecretEnc" text,
  "usernameEnc" text,
  "passwordEnc" text,
  connected boolean not null default false,
  "lastCheckedAt" text,
  "lastError" text,
  "updatedAt" text not null
);

-- ============================================================
-- BUSINESS_READINESS_ROADMAP.md Phase 8F — bKash create/execute lifecycle
-- ============================================================
-- One row per bKash checkout attempt started via the institution's own
-- connected gateway (institution_payment_gateways above). bKash's own
-- "Create Payment" call returns a paymentID and a checkout URL; the
-- guardian's browser (or, for an sms-topup, the admin's browser) is
-- redirected there, then bKash redirects back to our frontend with that
-- same paymentID — at which point our server calls bKash's "Execute
-- Payment" API and finalizes based on ITS response, never the redirect's
-- query params alone (those aren't signed, so trusting them directly
-- would let anyone fake a successful payment by hand-crafting the
-- callback URL). This row is what makes execute idempotent: once
-- status='completed', a second execute call for the same paymentID is a
-- no-op instead of double-crediting.
-- purpose distinguishes the two things Phase 8F reuses the same connected
-- gateway for: 'fee' (guardianId/studentId set, amount reduces that
-- student's due) vs 'sms-topup' (both null, amount credits sms_wallets —
-- the admin, not a guardian, is completing the checkout).
create table if not exists bkash_payment_intents (
  id integer generated by default as identity primary key,
  "paymentId" text,
  purpose text not null default 'fee',
  "guardianId" integer references guardian_accounts(id) on delete set null,
  "studentId" integer references students(id) on delete set null,
  amount integer not null,
  status text not null default 'initiated',
  "bkashTrxId" text,
  "createdAt" text not null,
  "completedAt" text
);

create unique index if not exists bkash_payment_intents_payment_id_unique
  on bkash_payment_intents ("paymentId") where "paymentId" is not null;
