create table if not exists students (
  id integer generated by default as identity primary key,
  name text not null,
  "nameEn" text default '',
  roll text not null,
  class text default '',
  dept text default 'হিফজ',
  type text default 'আবাসিক',
  fee integer default 1500,
  due integer default 0,
  phone text default '',
  blood text default 'O+',
  para integer default 0,
  status text default 'সক্রিয়'
);

alter table students add column if not exists "admissionNumber" text;
alter table students add column if not exists "admissionDate" text;
alter table students add column if not exists "academicYear" text;
alter table students add column if not exists session text;
alter table students add column if not exists section text;
alter table students add column if not exists "dateOfBirth" text;
alter table students add column if not exists "birthRegistrationNumber" text;
alter table students add column if not exists gender text;
alter table students add column if not exists religion text;
alter table students add column if not exists "studentPhoto" text;
alter table students add column if not exists "fatherName" text;
alter table students add column if not exists "fatherMobile" text;
alter table students add column if not exists "fatherOccupation" text;
alter table students add column if not exists "motherName" text;
alter table students add column if not exists "motherMobile" text;
alter table students add column if not exists "motherOccupation" text;
alter table students add column if not exists "guardianName" text;
alter table students add column if not exists "guardianRelationship" text;
alter table students add column if not exists "guardianMobile" text;
alter table students add column if not exists "presentAddress" text;
alter table students add column if not exists "permanentAddress" text;
alter table students add column if not exists district text;
alter table students add column if not exists upazila text;
alter table students add column if not exists "postOffice" text;
alter table students add column if not exists village text;
alter table students add column if not exists "previousInstitution" text;
alter table students add column if not exists "previousClass" text;
alter table students add column if not exists "admissionFee" integer default 0;
alter table students add column if not exists discount integer default 0;
alter table students add column if not exists documents jsonb default '{}'::jsonb;

-- Attendance-device integration (docs/ATTENDANCE_DEVICE_PLAN.md, Phase 1).
-- Ma­nually entered by an admin from the device's own enrollment menu (this
-- plan does not sync enrollment automatically from the device) — see
-- attendance_devices/attendance_logs below for how a punch is matched back
-- to a student via these two columns.
alter table students add column if not exists "fingerprintId" text;
alter table students add column if not exists "cardUid" text;

create unique index if not exists students_admission_number_unique
on students ("admissionNumber")
where "admissionNumber" is not null and "admissionNumber" <> '';

create unique index if not exists students_birth_registration_unique
on students ("birthRegistrationNumber")
where "birthRegistrationNumber" is not null and "birthRegistrationNumber" <> '';

-- Same partial-unique pattern as admissionNumber/birthRegistrationNumber
-- above: only enforced when the field is actually set (a student with no
-- device enrolled yet keeps a null/empty value, which never collides).
create unique index if not exists students_fingerprint_id_unique
on students ("fingerprintId")
where "fingerprintId" is not null and "fingerprintId" <> '';

create unique index if not exists students_card_uid_unique
on students ("cardUid")
where "cardUid" is not null and "cardUid" <> '';

create table if not exists attendance (
  id integer generated by default as identity primary key,
  "studentId" integer not null references students(id) on delete cascade,
  date text not null,
  status text not null,
  unique ("studentId", date)
);

-- Retroactive fix (2026-08): routes/attendance.js's POST / does a bulk
-- upsert with `ON CONFLICT ("studentId", date) DO UPDATE ...`, which
-- requires a unique index/constraint covering exactly those two columns to
-- exist — Postgres matches ON CONFLICT by column list, not by name. The
-- inline `unique ("studentId", date)` above only ever runs on a BRAND NEW
-- database (the CREATE TABLE itself is a no-op once the table already
-- exists, same caveat as the payments/income fixes above). Any institution
-- whose `attendance` table was created before that inline constraint was
-- added never got it, so every attendance save on that database hit
-- Postgres error 42P10 ("no unique or exclusion constraint matching the ON
-- CONFLICT specification") — an uncaught 500, attendance never saved. A
-- separate unique INDEX (not a same-named constraint, since the original's
-- auto-generated name isn't reliably known) satisfies ON CONFLICT just as
-- well and is safe to add unconditionally: `if not exists` makes it a
-- no-op on databases that already have this covered.
create unique index if not exists attendance_student_date_unique
on attendance ("studentId", date);

-- ============================================================
-- docs/ATTENDANCE_DEVICE_PLAN.md Phase 1 — fingerprint/card device support
-- ============================================================
-- One row per physical device (fingerprint scanner or card reader) an
-- institution has installed. "secretKey" is what routes/deviceAttendance.js
-- checks a punch request against before trusting it (this table's own
-- auth, since device requests don't carry a normal user JWT — see the
-- plan doc's Phase 2 for why). "active" lets an admin disable a lost/
-- decommissioned device without deleting its punch history.
create table if not exists attendance_devices (
  id integer generated by default as identity primary key,
  "deviceId" text not null,
  "secretKey" text not null,
  name text default '',
  location text default '',
  active boolean not null default true,
  "createdAt" text not null
);

create unique index if not exists attendance_devices_device_id_unique
on attendance_devices ("deviceId");

-- docs/ATTENDANCE_DEVICE_CENTRALIZED_INGESTION_PLAN.md, Phase 1 — which
-- kind of device this is ('push_adms' | 'key_reader' | 'pull_sdk', see
-- registry.device_registry's comment in registry_schema.sql for what each
-- means). Idempotent add for existing tenant schemas; new schemas get it
-- straight from the create table above.
alter table attendance_devices add column if not exists protocol text not null default 'push_adms';

-- Raw punch events, one row per scan — never updated or deleted, kept as
-- the audit trail behind the daily attendance.status summary above.
-- routes/deviceAttendance.js computes "first punch of the day" / "last
-- punch of the day" from this table rather than storing entry/exit
-- directly, so a student punching more than twice in a day doesn't lose
-- data. "direction" is nullable because most fingerprint/card devices
-- don't distinguish in/out at the hardware level (see plan doc, Phase 1
-- assumption on entry/exit) — the app derives it from ordering when null.
-- "studentId" is nullable and "matched"/"identifier" exist so an UNKNOWN
-- fingerprintId/cardUid (no matching student) can still be logged instead
-- of silently rejected with nothing recorded — added 2026-08-12 so the
-- Phase 4 kiosk can show "ছাত্র খুঁজে পাওয়া যায়নি" for a real failed scan,
-- which needs *some* row to poll for (see plan doc Phase 4 + the "known
-- gap" note that shipped with the first Phase 4 delivery).
create table if not exists attendance_logs (
  id integer generated by default as identity primary key,
  "studentId" integer references students(id) on delete cascade,
  "deviceId" integer references attendance_devices(id) on delete set null,
  "punchAt" text not null,
  direction text,
  method text not null default 'fingerprint',
  matched boolean not null default true,
  identifier text
);

create index if not exists attendance_logs_student_punch_idx
on attendance_logs ("studentId", "punchAt");

-- Idempotent migration for tenants provisioned before the 2026-08-12
-- change above (mirrors the payments.studentId nullable fix pattern just
-- below in this file) — no-op on a brand-new database, which already gets
-- the nullable column/new columns from the create-table statement itself.
alter table attendance_logs alter column "studentId" drop not null;
alter table attendance_logs add column if not exists matched boolean not null default true;
alter table attendance_logs add column if not exists identifier text;

create table if not exists payments (
  id integer generated by default as identity primary key,
  "studentId" integer references students(id) on delete set null,
  student text not null,
  roll text not null,
  amount integer not null,
  date text not null,
  receipt text not null,
  method text default 'Cash',
  status text default 'Completed'
);

create unique index if not exists payments_receipt_unique on payments (receipt);

-- Offline-first Phase 5 (fee collection): when a payment syncs and the
-- student's due is already 0 (most likely two staff collected the same
-- fee while both were offline), the row is kept with status = 'Flagged'
-- and this reason instead of being silently double-booked — see
-- server/src/routes/payments.js's isConflict branch and the
-- POST /:id/resolve-flag endpoint that clears it.
alter table payments add column if not exists "flagReason" text;

-- BUSINESS_READINESS_ROADMAP.md Phase 1 (2026-08-05): studentId used to be
-- "not null ... on delete cascade", so deleting a student silently deleted
-- all of their payment/receipt history too — a real problem for a
-- financial/audit record (income.studentId had the same issue and was
-- already fixed to "on delete set null", see the income table above; this
-- brings payments in line with it). student/roll are already stored as a
-- denormalized snapshot on this table (see the comment above the results
-- table), so a receipt still shows the right name/roll even after
-- studentId goes null. This block is a no-op on a brand-new database
-- (matches the create table statement above already) and only does real
-- work on a database created before this fix.
alter table payments alter column "studentId" drop not null;
alter table payments drop constraint if exists "payments_studentId_fkey";
alter table payments add constraint "payments_studentId_fkey"
  foreign key ("studentId") references students(id) on delete set null;

create table if not exists income (
  id integer generated by default as identity primary key,
  category text not null,
  amount integer not null,
  date text not null,
  note text default '',
  method text default 'Cash',
  receipt text not null,
  "studentId" integer references students(id) on delete set null,
  status text default 'Completed'
);

create unique index if not exists income_receipt_unique on income (receipt);

create table if not exists expenses (
  id integer generated by default as identity primary key,
  cat text not null,
  amount integer not null,
  date text not null,
  note text default ''
);

create table if not exists hifz_logs (
  id integer generated by default as identity primary key,
  "studentId" integer not null references students(id) on delete cascade,
  date text not null,
  sabaq text default ''
);

-- Exam results. "class"/"roll"/"studentName" are stored as a snapshot at
-- save time (same denormalization pattern as payments.student/payments.roll
-- above) so a result stays correct even if a student later changes class or
-- is edited. "published" gates public visibility: staff can enter and
-- correct marks freely, and results only become visible on the public
-- Result Lookup page once explicitly published.
create table if not exists results (
  id integer generated by default as identity primary key,
  "studentId" integer not null references students(id) on delete cascade,
  "examName" text not null,
  year text not null,
  class text not null,
  roll text not null,
  "studentName" text not null,
  subjects jsonb not null default '[]',
  "totalMarks" integer default 0,
  "obtainedMarks" integer default 0,
  gpa text default '',
  grade text default '',
  published integer default 0,
  "updatedAt" timestamptz default now(),
  unique ("studentId", "examName", year)
);

create index if not exists results_lookup_idx on results (class, roll, "examName", published);

create table if not exists settings (
  key text primary key,
  value text not null
);

create table if not exists users (
  id integer generated by default as identity primary key,
  name text not null,
  role text not null default 'Teacher',
  email text unique,
  "passwordHash" text,
  "isProtected" integer default 0
);

-- Account-level brute-force lockout (task 1.2). Added via ALTER because the
-- CREATE TABLE above is a no-op once the table already exists on deployed DBs.
alter table users add column if not exists "failedLoginAttempts" integer not null default 0;
alter table users add column if not exists "lockedUntil" timestamptz;

-- Reports > কল-লিস্ট ফিচার (docs/CALL_LIST_PLAN.md, Phase 1): কোন ছাত্রকে
-- কোন ক্যালেন্ডার মাসে ("callMonth", 'YYYY-MM') কল দেওয়া হয়েছে তার রেকর্ড।
-- একটা row থাকা মানেই সেই মাসে কল হয়েছে ("সবুজ") — row না থাকলে "এখনো হয়নি"
-- ("লাল")। নতুন মাস শুরু হলে সেই মাসের জন্য কোনো row থাকে না বলে মার্ক
-- স্বয়ংক্রিয়ভাবে আবার "লাল" হয়ে যায়, পুরনো মাসের row মোছার দরকার নেই।
-- users টেবিলের পরে রাখা হয়েছে যাতে "calledBy" ফরেন-কি রেফারেন্স রেজলভ হয়
-- (এই ফাইলের স্টেটমেন্টগুলো ওপর থেকে নিচে একটাই ব্যাচে রান হয়, তাই referenced
-- টেবিল আগে তৈরি থাকা লাগে — db.js-এর initSchema() কমেন্ট দেখুন)।
create table if not exists student_call_log (
  id integer generated by default as identity primary key,
  "studentId" integer not null references students(id) on delete cascade,
  "callMonth" text not null,
  "calledBy" integer references users(id) on delete set null,
  "calledAt" timestamptz not null default now(),
  unique ("studentId", "callMonth")
);

create table if not exists password_resets (
  id integer generated by default as identity primary key,
  "userId" integer not null references users(id) on delete cascade,
  token text not null unique,
  "expiresAt" text not null
);

create table if not exists delete_requests (
  id integer generated by default as identity primary key,
  "entityType" text not null,
  "entityId" integer not null,
  label text not null,
  amount integer default 0,
  "requestedBy" integer,
  "requestedByName" text default '',
  status text not null default 'pending',
  "createdAt" text not null,
  "resolvedAt" text,
  "resolvedBy" integer,
  payload text default ''
);

create unique index if not exists delete_requests_pending_unique
on delete_requests ("entityType", "entityId", status)
where status = 'pending';

create table if not exists receipt_counters (
  "key" text primary key,
  value bigint not null default 0
);

-- Offline-first foundation (Phase 0): lets the idempotency middleware
-- (server/src/middleware/idempotency.js) recognize a retried mutation —
-- e.g. a payment or admission submitted while offline, queued client-side,
-- and resent once the connection returns — as the SAME request rather than
-- creating a duplicate. clientRequestId is generated in the browser (see
-- client/src/lib/api.ts) and sent as the X-Client-Request-Id header.
create table if not exists sync_requests (
  "clientRequestId" text primary key,
  route text not null,
  "statusCode" integer not null,
  response jsonb default '{}'::jsonb,
  "createdAt" text not null
);

create table if not exists audit_logs (
  id integer generated by default as identity primary key,
  "action" text not null,
  "actorId" integer,
  "actorName" text default '',
  "actorRole" text default '',
  "entityType" text default '',
  "entityId" integer,
  label text default '',
  details text default '',
  "createdAt" text not null
);

create index if not exists audit_logs_created_at_idx on audit_logs ("createdAt" desc);

create table if not exists backup_restore_events (
  id integer generated by default as identity primary key,
  event text not null,
  status text not null,
  "requestedBy" integer,
  "requestedByName" text default '',
  "backupVersion" integer,
  "backupFormat" text default '',
  report jsonb default '{}'::jsonb,
  error text default '',
  "createdAt" text not null
);

-- Public "ভর্তি" (admission) form submissions from the marketing site.
-- Distinct from `students`: these are unverified inbound inquiries a staff
-- member reviews before a real student record is created.
create table if not exists admissions (
  id integer generated by default as identity primary key,
  "studentName" text not null,
  "studentNameEn" text default '',
  "dateOfBirth" text default '',
  gender text default '',
  "className" text not null,
  "guardianName" text not null,
  "guardianPhone" text not null,
  "presentAddress" text default '',
  "previousInstitution" text default '',
  note text default '',
  status text not null default 'Pending',
  "createdAt" text not null
);

create index if not exists admissions_created_at_idx on admissions ("createdAt" desc);

-- In-app notification center. A row is either targeted at specific roles
-- (targetRoles, e.g. new admission -> ["Admin","Super Admin"]) or at one
-- specific user (targetUserId, e.g. "your delete request was approved").
-- Read state is tracked per-user in notification_reads rather than a single
-- boolean on this table, since the same role-targeted notification can be
-- read by one Admin and still unread for another.
create table if not exists notifications (
  id integer generated by default as identity primary key,
  type text not null,
  title text not null,
  body text default '',
  "entityType" text default '',
  "entityId" integer,
  link text default '',
  "targetRoles" text[] not null default '{}',
  "targetUserId" integer references users(id) on delete cascade,
  "createdAt" text not null
);

create index if not exists notifications_created_at_idx on notifications ("createdAt" desc);

create table if not exists notification_reads (
  "notificationId" integer not null references notifications(id) on delete cascade,
  "userId" integer not null references users(id) on delete cascade,
  "readAt" text not null,
  primary key ("notificationId", "userId")
);

-- ============================================================
-- Guardian Portal + Teacher Class-Scoping — Step 1 (DB schema)
-- ============================================================
-- Separate login identity from `users` (staff). A guardian account is
-- created via self-signup (4-field match: name/roll/class/guardianMobile
-- against an existing students row — see the signup endpoint added in
-- Step 2) and starts as "pending" or "active" depending on match strength,
-- same tri-state pattern as delete_requests.status above.
create table if not exists guardian_accounts (
  id integer generated by default as identity primary key,
  name text not null,
  mobile text,
  email text,
  "passwordHash" text not null,
  status text not null default 'pending',
  "failedLoginAttempts" integer not null default 0,
  "lockedUntil" timestamptz,
  "createdAt" text not null
);

-- A guardian can be blank on whichever contact field they didn't sign up
-- with, so uniqueness is partial (mirrors students_admission_number_unique
-- above) rather than a plain unique column constraint.
create unique index if not exists guardian_accounts_mobile_unique
on guardian_accounts (mobile)
where mobile is not null and mobile <> '';

create unique index if not exists guardian_accounts_email_unique
on guardian_accounts (email)
where email is not null and email <> '';

-- Many-to-many: one guardian can be linked to more than one child ("আরেকটি
-- সন্তান যুক্ত করুন" in Step 2), and — rare but possible with blended
-- families — a student could in principle have more than one linked
-- guardian account, so this is a junction table rather than a single FK
-- column on either side.
create table if not exists guardian_students (
  "guardianId" integer not null references guardian_accounts(id) on delete cascade,
  "studentId" integer not null references students(id) on delete cascade,
  "createdAt" text not null,
  primary key ("guardianId", "studentId")
);

create index if not exists guardian_students_student_idx on guardian_students ("studentId");

-- Step 2 Part 2: a later child-link request may need Admin review even when
-- the guardian account itself is already active. Existing links (including
-- links created by Step 2 Part 1) remain active by default.
alter table guardian_students add column if not exists status text not null default 'active';
alter table guardian_students add column if not exists "matchCount" integer;
alter table guardian_students add column if not exists "reviewedAt" text;
alter table guardian_students add column if not exists "reviewedBy" integer references users(id) on delete set null;

create index if not exists guardian_students_status_idx on guardian_students (status);

-- Which classes a Teacher may see/act on. Only Super Admin/Admin write this
-- (via /api/users, permission "settings" — Step 3), a Teacher never edits
-- their own assignments. `class` stores the same English slug value as
-- students.class (see lib/classOptions.js), not a foreign key since the
-- class/jamaat list itself lives in settings.classOptions (JSON), not its
-- own table.
create table if not exists teacher_class_assignments (
  id integer generated by default as identity primary key,
  "userId" integer not null references users(id) on delete cascade,
  class text not null,
  "createdAt" text not null,
  unique ("userId", class)
);

create index if not exists teacher_class_assignments_user_idx on teacher_class_assignments ("userId");

-- ============================================================
-- docs/STAFF_ATTENDANCE_PLAN.md, Phase 1 — staff registry + staff
-- attendance. Deliberately SEPARATE from `users` above (software login
-- accounts) — most staff (peon, guard, ayah, ...) never need a login, so
-- `staff` carries the actual employee record (name/phone/designation/
-- joining date) with an OPTIONAL "userId" link to `users` for the subset
-- who do have a login. See the plan doc §2 for the full rationale.
-- ============================================================
create table if not exists staff (
  id integer generated by default as identity primary key,
  name text not null,
  phone text default '',
  -- Free text (with a client-side preset dropdown — শিক্ষক/হিসাবরক্ষক/
  -- পিয়ন/দারোয়ান/আয়া/অন্যান্য) rather than an enum: an institution's
  -- actual designation titles vary too much to whitelist server-side,
  -- same reasoning as students.dept being free text elsewhere.
  designation text not null,
  -- Only meaningful when designation is teaching-related; ties into the
  -- existing class/jamaat master list (lib/classOptions.js) — not a
  -- foreign key for the same reason teacher_class_assignments.class isn't.
  class text default '',
  "joiningDate" text default '',
  -- Reserved for a later phase (plan doc §6, open question 4) — schema
  -- column exists now so it doesn't need a second migration later, but no
  -- upload UI ships with Phase 5.
  photo text default '',
  status text not null default 'Active',
  "userId" integer references users(id) on delete set null,
  note text default '',
  "createdAt" text not null
);

create index if not exists staff_user_idx on staff ("userId");

-- docs/STAFF_ATTENDANCE_PLAN.md, Phase 7 — fingerprint/card device support
-- for staff, same pattern as students.fingerprintId/cardUid above (Phase
-- 1). Manually entered by an admin (or captured via the same "স্ক্যান করে
-- বসান" flow Students.tsx already uses — see lib/devicePunch.js's staff
-- lookup fallback for how a punch is matched back to a staff row via
-- these two columns).
alter table staff add column if not exists "fingerprintId" text;
alter table staff add column if not exists "cardUid" text;

-- Same partial-unique pattern as students_fingerprint_id_unique/
-- students_card_uid_unique — only enforced when actually set, so a staff
-- member with no device enrolled yet keeps a null value, which never
-- collides.
create unique index if not exists staff_fingerprint_id_unique
on staff ("fingerprintId")
where "fingerprintId" is not null and "fingerprintId" <> '';

create unique index if not exists staff_card_uid_unique
on staff ("cardUid")
where "cardUid" is not null and "cardUid" <> '';

-- docs/STAFF_ATTENDANCE_PLAN.md, Phase 7 — lets a device punch attribute
-- to a staff row instead of a student one. Added here (after `staff`
-- exists) rather than alongside attendance_logs' own create table above,
-- since the FK needs `staff` to already exist. Nullable + on delete set
-- null, same reasoning as "studentId" above: exactly one of studentId/
-- staffId is set on a matched row (or neither, on an unmatched scan —
-- see lib/devicePunch.js).
alter table attendance_logs add column if not exists "staffId" integer references staff(id) on delete cascade;

create index if not exists attendance_logs_staff_punch_idx
on attendance_logs ("staffId", "punchAt");

-- Same shape as `attendance` above (studentId -> staffId), including the
-- same ON CONFLICT-safe unique index pattern (see the "Retroactive fix"
-- comment on `attendance` above for why the index is separate from an
-- inline `unique (...)` — this table starts out correct on new databases,
-- but the index is still declared explicitly rather than relied upon
-- implicitly, so ON CONFLICT below is guaranteed to have something to match).
create table if not exists staff_attendance (
  id integer generated by default as identity primary key,
  "staffId" integer not null references staff(id) on delete cascade,
  date text not null,
  status text not null,
  unique ("staffId", date)
);

create unique index if not exists staff_attendance_staff_date_unique
on staff_attendance ("staffId", date);

-- ============================================================
-- docs/SHIFT_SCHEDULE_PLAN.md, Phase 1 — shift/schedule master data +
-- class/staff assignment + entry/exit time columns. Institution-defined
-- time blocks (e.g. "সকাল শিফট" 08:00-12:00) so a device punch's time can
-- be compared against a start time to decide উপস্থিত vs দেরিতে
-- automatically instead of only ever being manually chosen (see plan §2
-- for why: lib/devicePunch.js currently hardcodes status='উপস্থিত' on
-- every punch, with no time comparison anywhere in the project).
-- ============================================================
create table if not exists shifts (
  id integer generated by default as identity primary key,
  name text not null,
  "nameEn" text default '',
  "startTime" text not null,       -- 'HH:MM', 24-hour
  "endTime" text not null,
  "graceMinutes" integer not null default 0,
  active boolean not null default true,
  "createdAt" text not null
);

-- Class/jamaat -> shift mapping. The class list itself lives as a JSON
-- blob in settings (lib/classOptions.js/classTree.js), not its own table,
-- so this keys on the class slug text directly rather than a real FK to a
-- classes table (none exists) — see plan §Phase 1 for the orphan-mapping
-- tradeoff (harmless: an orphaned mapping just means that class's students
-- fall back to no-shift, same as never having been assigned one).
create table if not exists class_shifts (
  class text primary key,
  "shiftId" integer not null references shifts(id) on delete cascade
);

-- Nullable + on delete set null: a staff member with no shift assigned
-- yet keeps working exactly as before (lib/attendanceSchedule.js's
-- resolveShiftForStaff() returning null skips lateness computation, see
-- Phase 4), so this is a purely additive column.
alter table staff add column if not exists "shiftId" integer references shifts(id) on delete set null;

-- Daily entry/exit time, alongside the existing status column. Populated
-- by lib/devicePunch.js on the first (entryTime) and every subsequent
-- (exitTime) punch of the day; also settable from the manual
-- attendance/staffAttendance UI once Phase 7/8 land. Text, not timestamp,
-- to match every other time-ish column in this schema (joiningDate,
-- createdAt, punchAt are all `text`) rather than introducing a new type
-- convention for just these two columns.
alter table attendance add column if not exists "entryTime" text;
alter table attendance add column if not exists "exitTime" text;
alter table staff_attendance add column if not exists "entryTime" text;
alter table staff_attendance add column if not exists "exitTime" text;

-- Class-broadcast model (Step 4): a Teacher posts once per class instead of
-- once per student; the guardian feed is produced by joining this table
-- against guardian_students/students at read time, so there is no
-- per-guardian fan-out row to keep in sync.
create table if not exists class_posts (
  id integer generated by default as identity primary key,
  type text not null,
  class text not null,
  "teacherId" integer references users(id) on delete set null,
  title text not null,
  body text default '',
  attachments jsonb default '[]'::jsonb,
  "createdAt" text not null
);

-- Multi-target audience (ad-hoc — sidebar "নোটিশ ও অ্যাসাইনমেন্ট" <-> public
-- site notices connector, docs/CURRENT_TASK.md). `class` above stays exactly
-- as it was (a Teacher's single-class post still only ever writes that one
-- column, unchanged) — these are additive columns only Admin/Super Admin can
-- populate (see routes/assignments.js), so old rows/queries against `class`
-- keep working untouched.
--   "targetClasses"     — jsonb array of leaf class `en` slugs. A "সকল বিভাগ"
--                          (whole department) pick is expanded into its leaf
--                          classes client-side before it ever reaches here,
--                          so this table never needs to know about
--                          department-level grouping itself.
--   "allClasses"         — true means every active-linked guardian, regardless
--                          of which class(es) targetClasses lists.
--   "publicSite"          — true means this post was also mirrored onto the
--                          public /notices page (content.notices) at creation
--                          time — see lib/siteContent.js's addNoticeAndPublish.
--   "guardianStudentIds"  — jsonb array of student ids, for "নির্দিষ্ট
--                          গার্ডিয়ান": the guardian(s) of these specific
--                          students, regardless of class.
alter table class_posts add column if not exists "targetClasses" jsonb not null default '[]'::jsonb;
alter table class_posts add column if not exists "allClasses" boolean not null default false;
alter table class_posts add column if not exists "publicSite" boolean not null default false;
alter table class_posts add column if not exists "guardianStudentIds" jsonb not null default '[]'::jsonb;

create index if not exists class_posts_class_created_idx on class_posts (class, "createdAt" desc);
create index if not exists class_posts_all_classes_idx on class_posts ("allClasses") where "allClasses" = true;

-- Step 4: per-guardian read-tracking for the class-broadcast feed. The plan
-- called for reusing the existing notifications/notification_reads tables
-- for this, but notification_reads."userId" (and notifications."targetUserId")
-- are hard FK'd to users(id) — the STAFF table — so a guardian_accounts.id
-- can never be stored there safely (either the FK insert fails outright, or
-- if the id ranges happened to overlap it would silently point at the
-- wrong staff member). This is the guardian-side equivalent instead: same
-- shape as notification_reads, but keyed to guardian_accounts and
-- class_posts. A missing row = unread, same "absence means unread" contract
-- notification_reads already uses for staff.
create table if not exists class_post_reads (
  "postId" integer not null references class_posts(id) on delete cascade,
  "guardianId" integer not null references guardian_accounts(id) on delete cascade,
  "readAt" text not null,
  primary key ("postId", "guardianId")
);

create index if not exists class_post_reads_guardian_idx on class_post_reads ("guardianId");

-- ============================================================
-- Guardian Reminder Messenger (ad-hoc — see docs/CURRENT_TASK.md, not a
-- BUSINESS_READINESS_ROADMAP phase)
-- ============================================================
-- Admin-authored reminder definitions. Turned into actual per-guardian
-- guardian_messages rows by lib/guardianReminders.js's dispatchDueReminders
-- — scheduled the same setInterval way billing.js's expiry scan is
-- (AGENTS.md Rule 5: no new cron npm dependency), plus a manual
-- POST /api/guardian-reminders/dispatch button for on-demand sends.
-- Deliberately NOT reusing class_posts: a reminder needs its own targeting
-- (all/class/single-student) and schedule (once/daily/specificDate)
-- columns class_posts has no reason to carry.
create table if not exists guardian_reminders (
  id integer generated by default as identity primary key,
  title text not null,
  body text not null default '',
  "targetType" text not null default 'all', -- 'all' | 'class' | 'student' | 'feeDue' | 'lateArrival' | 'attendanceMissing' | 'selectedStudents'
  "targetClass" text,
  "targetStudentId" integer references students(id) on delete cascade,
  "scheduleType" text not null default 'once', -- 'once' | 'daily' | 'specificDate'
  "scheduleDate" text, -- 'YYYY-MM-DD'; required for 'specificDate', unused otherwise
  active boolean not null default true,
  "createdBy" integer references users(id) on delete set null,
  "createdAt" text not null,
  "lastSentAt" text
);

create index if not exists guardian_reminders_active_idx on guardian_reminders (active);

-- docs/CONDITIONAL_REMINDERS_PLAN.md Phase 1 — conditional/automatic
-- reminders (feeDue/lateArrival/attendanceMissing/selectedStudents). All
-- three are nullable/defaulted so every existing reminder row keeps its
-- exact current behavior untouched: scheduleTime null = fire as soon as
-- the daily sweep sees it's due (today's old behavior), intervalDays
-- defaults to 1 = "every day" (today's old 'daily' behavior).
alter table guardian_reminders add column if not exists "scheduleTime" text; -- 'HH:MM', 24hr
alter table guardian_reminders add column if not exists "intervalDays" integer not null default 1; -- only consulted when scheduleType='daily'
alter table guardian_reminders add column if not exists "selectedStudentIds" jsonb; -- targetType='selectedStudents' only; array of students.id

-- One row per guardian per dispatch — a 'daily' reminder targeting 200
-- guardians produces 200 rows every day it fires. Unlike class_posts (a
-- join-at-read-time feed), a reminder's whole point is per-guardian
-- delivery + per-guardian read state, so fan-out at write time is the
-- right tradeoff here.
create table if not exists guardian_messages (
  id integer generated by default as identity primary key,
  "reminderId" integer references guardian_reminders(id) on delete set null,
  "guardianId" integer not null references guardian_accounts(id) on delete cascade,
  title text not null,
  body text not null default '',
  "createdAt" text not null,
  "readAt" text
);

create index if not exists guardian_messages_guardian_idx on guardian_messages ("guardianId");
create index if not exists guardian_messages_reminder_idx on guardian_messages ("reminderId", "createdAt");

-- ============================================================
-- Guardian Push Notifications (docs/PUSH_NOTIFICATION_PLAN.md — Phase 1)
-- ============================================================
-- One row per subscribed browser/device per guardian (a guardian logged in
-- on both their phone and a desktop browser gets two rows, both receive a
-- push). "endpoint" is the browser's own unique per-subscription push URL
-- — used as the natural upsert key so re-subscribing the same
-- browser/device (e.g. after clearing site data) updates the existing row
-- instead of accumulating duplicates. "p256dh"/"auth" are the
-- browser-generated encryption keys the Web Push spec requires to encrypt
-- the payload — meaningless without the matching VAPID private key
-- (server/src/lib/guardianPush.js, Phase 2), so no additional encryption
-- is needed on this table itself. A subscription is deleted outright (not
-- soft-deleted/deactivated) either when the guardian explicitly
-- unsubscribes or when a push attempt gets back 404/410 Gone from the
-- push service (guardianPush.js's own cleanup, not here) — there is no
-- reason to keep a dead subscription row around.
create table if not exists guardian_push_subscriptions (
  id integer generated by default as identity primary key,
  "guardianId" integer not null references guardian_accounts(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  "userAgent" text,
  "createdAt" text not null
);

create index if not exists guardian_push_subscriptions_guardian_idx on guardian_push_subscriptions ("guardianId");

-- Same idea as guardian_push_subscriptions above, but for staff/admin
-- accounts (users table) instead of guardian_accounts — used to alert
-- Super Admin's own browser/phone the moment an automatic backup fails or
-- can't reach Google Drive (lib/adminPush.js), since that failure would
-- otherwise only ever surface if someone happens to open Settings and look.
-- Shares the same VAPID keypair/env vars as guardian push (Web Push
-- doesn't require a separate keypair per audience).
create table if not exists admin_push_subscriptions (
  id integer generated by default as identity primary key,
  "userId" integer not null references users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  "userAgent" text,
  "createdAt" text not null
);

create index if not exists admin_push_subscriptions_user_idx on admin_push_subscriptions ("userId");

-- ============================================================
-- BUSINESS_READINESS_ROADMAP.md Phase 8A — SMS wallet + ledger
-- ============================================================
-- Schema-per-tenant means this table lives inside one institution's own
-- schema (search_path-scoped, same as every other table above) — so unlike
-- a shared multi-tenant table, it does NOT need an "institutionId" column
-- to separate rows between institutions. Each tenant schema, and the
-- single-tenant `public` schema, gets exactly one wallet row: application
-- code (smsSender.js, Phase 8B) always reads/updates that one row rather
-- than looking one up by institution. The row itself is inserted once, at
-- provisioning time (tenantProvision.js for a new tenant; db.js's initDb()
-- for a single-tenant deployment) — this CREATE TABLE only defines the
-- shape, same convention as `settings` (a table this file never seeds
-- rows into either).
create table if not exists sms_wallets (
  id integer generated by default as identity primary key,
  balance_taka numeric(12,2) not null default 0,
  "updatedAt" timestamptz not null default now()
);

-- Ledger of every wallet change (type: 'topup' | 'deduct'). smsCount is
-- null for a topup row (money added, no SMS sent yet) and set for a deduct
-- row (how many SMS that deduction paid for). reference is free text —
-- e.g. a manual top-up's bKash Trx ID (8D), or the SMS provider's own
-- message/batch id (8B) — kept as a string since the two sources have
-- unrelated id formats. createdAt is text (ISO string), matching every
-- other ledger/log table in this file (audit_logs, notifications,
-- admissions) rather than the timestamptz style used for point-in-time
-- fields like sms_wallets."updatedAt" above.
create table if not exists sms_transactions (
  id integer generated by default as identity primary key,
  type text not null,
  "amountTaka" numeric(12,2) not null,
  "smsCount" integer,
  reference text default '',
  "createdAt" text not null
);

-- BUSINESS_READINESS_ROADMAP.md Phase 8D — manual top-up requests. An
-- institution-admin submits a bKash Trx ID (type='topup', status='pending'
-- row, balance NOT touched yet); a platform Super-Admin checks the real
-- bKash inbox and approves/rejects from the platform panel
-- (routes/platform.js, tenant-scoped via migrateTenants.withTenantSchema).
-- Only approval credits sms_wallets.balance_taka. Every row inserted
-- before this phase (Phase 8B's deduct rows) has no explicit status, so
-- the default keeps them correctly classified as already-settled/
-- "confirmed" rather than retroactively looking "pending".
alter table sms_transactions add column if not exists "status" text not null default 'confirmed';

create index if not exists sms_transactions_created_at_idx on sms_transactions ("createdAt" desc);

-- ============================================================
-- BUSINESS_READINESS_ROADMAP.md Phase 8E — bKash self-connect
-- ============================================================
-- One row per institution's own bKash agent/merchant credentials
-- (Bring-Your-Own-Account — see roadmap Phase 8 intro). Schema-per-tenant
-- means this table lives inside one institution's own schema, same as
-- sms_wallets above, so it needs no institutionId column either — at most
-- one row ever exists here, upserted by routes/paymentGateway.js.
-- Credentials are NEVER stored in plaintext: appKey/appSecret/username/
-- password are each encrypted with lib/gatewayCredentialCrypto.js
-- (AES-256-GCM, same algorithm as lib/backupEncryption.js but for short
-- strings instead of files, keyed by the separate GATEWAY_CREDENTIAL_KEY
-- env var so a leaked backup-encryption key alone can't decrypt these).
-- "connected" only flips true after a live grant-token call against
-- bKash's API actually succeeds (see bkashGateway.js) — submitting the
-- form alone does not set it.
create table if not exists institution_payment_gateways (
  id integer generated by default as identity primary key,
  provider text not null default 'bkash',
  "appKeyEnc" text,
  "appSecretEnc" text,
  "usernameEnc" text,
  "passwordEnc" text,
  connected boolean not null default false,
  "lastCheckedAt" text,
  "lastError" text,
  "updatedAt" text not null
);

-- ============================================================
-- BUSINESS_READINESS_ROADMAP.md Phase 8F — bKash create/execute lifecycle
-- ============================================================
-- One row per bKash checkout attempt started via the institution's own
-- connected gateway (institution_payment_gateways above). bKash's own
-- "Create Payment" call returns a paymentID and a checkout URL; the
-- guardian's browser (or, for an sms-topup, the admin's browser) is
-- redirected there, then bKash redirects back to our frontend with that
-- same paymentID — at which point our server calls bKash's "Execute
-- Payment" API and finalizes based on ITS response, never the redirect's
-- query params alone (those aren't signed, so trusting them directly
-- would let anyone fake a successful payment by hand-crafting the
-- callback URL). This row is what makes execute idempotent: once
-- status='completed', a second execute call for the same paymentID is a
-- no-op instead of double-crediting.
-- purpose distinguishes the two things Phase 8F reuses the same connected
-- gateway for: 'fee' (guardianId/studentId set, amount reduces that
-- student's due) vs 'sms-topup' (both null, amount credits sms_wallets —
-- the admin, not a guardian, is completing the checkout).
create table if not exists bkash_payment_intents (
  id integer generated by default as identity primary key,
  "paymentId" text,
  purpose text not null default 'fee',
  "guardianId" integer references guardian_accounts(id) on delete set null,
  "studentId" integer references students(id) on delete set null,
  amount integer not null,
  status text not null default 'initiated',
  "bkashTrxId" text,
  "createdAt" text not null,
  "completedAt" text
);

create unique index if not exists bkash_payment_intents_payment_id_unique
  on bkash_payment_intents ("paymentId") where "paymentId" is not null;

-- ============================================================
-- docs/OWN_SIM_BULK_SMS_GATEWAY_PLAN.md Phase 1 — own-phone/SIM bulk SMS
-- ============================================================
-- Completely separate, parallel system from sms_wallets/sms_transactions
-- above (BulkSMSBD-based paid reseller flow) — no wallet, no deduction;
-- cost sits on the institution's own SIM balance. Voice-call-broadcast is
-- out of scope for this task (see plan doc).

-- One row per institution's own SMSGate (sms-gate.app) Cloud API account
-- (Bring-Your-Own-Device, same shape as institution_payment_gateways
-- above). Schema-per-tenant, so at most one row ever exists here, upserted
-- by routes/ownSmsGateway.js. username/password are encrypted with the
-- existing lib/gatewayCredentialCrypto.js (AES-256-GCM,
-- GATEWAY_CREDENTIAL_KEY) — reused as-is, not a new crypto module, since
-- this protects the same class of secret (a third-party account
-- credential) that table already exists to protect. "connected" only
-- flips true after a live verifyCredentials() call against SMSGate's API
-- actually succeeds — submitting the form alone does not set it.
create table if not exists own_sms_gateway (
  id integer generated by default as identity primary key,
  provider text not null default 'smsgate',
  "usernameEnc" text,
  "passwordEnc" text,
  connected boolean not null default false,
  "lastCheckedAt" text,
  "lastError" text,
  "updatedAt" text not null
);

-- Manual name+phone contact list for the broadcast-send feature
-- (routes/smsContacts.js). Deliberately unrelated to students/
-- guardian_students — see plan doc design decision #2: standalone,
-- manually-maintained list, no auto-import from student data.
create table if not exists sms_contacts (
  id integer generated by default as identity primary key,
  name text not null,
  phone text not null,
  "groupName" text default '',
  "createdAt" text not null
);

create index if not exists sms_contacts_group_name_idx on sms_contacts ("groupName");

-- Summary history of each broadcast send (routes/sms.js's POST
-- /broadcast) — one row per send, not one row per recipient (see that
-- route's recordAudit() comment for the same per-batch-not-per-contact
-- reasoning).
create table if not exists sms_broadcast_logs (
  id integer generated by default as identity primary key,
  "messageTemplate" text not null,
  "recipientCount" integer not null default 0,
  "sentCount" integer not null default 0,
  "failedCount" integer not null default 0,
  "sentBy" integer,
  "createdAt" text not null
);

create index if not exists sms_broadcast_logs_created_at_idx on sms_broadcast_logs ("createdAt" desc);
