create table if not exists students (
  id integer generated by default as identity primary key,
  name text not null,
  "nameEn" text default '',
  roll text not null,
  class text default '',
  dept text default 'হিফজ',
  type text default 'আবাসিক',
  fee integer default 1500,
  due integer default 0,
  phone text default '',
  blood text default 'O+',
  para integer default 0,
  status text default 'সক্রিয়'
);

alter table students add column if not exists "admissionNumber" text;
alter table students add column if not exists "admissionDate" text;
alter table students add column if not exists "academicYear" text;
alter table students add column if not exists session text;
alter table students add column if not exists section text;
alter table students add column if not exists "dateOfBirth" text;
alter table students add column if not exists "birthRegistrationNumber" text;
alter table students add column if not exists gender text;
alter table students add column if not exists religion text;
alter table students add column if not exists "studentPhoto" text;
alter table students add column if not exists "fatherName" text;
alter table students add column if not exists "fatherMobile" text;
alter table students add column if not exists "fatherOccupation" text;
alter table students add column if not exists "motherName" text;
alter table students add column if not exists "motherMobile" text;
alter table students add column if not exists "motherOccupation" text;
alter table students add column if not exists "guardianName" text;
alter table students add column if not exists "guardianRelationship" text;
alter table students add column if not exists "guardianMobile" text;
alter table students add column if not exists "presentAddress" text;
alter table students add column if not exists "permanentAddress" text;
alter table students add column if not exists district text;
alter table students add column if not exists upazila text;
alter table students add column if not exists "postOffice" text;
alter table students add column if not exists village text;
alter table students add column if not exists "previousInstitution" text;
alter table students add column if not exists "previousClass" text;
alter table students add column if not exists "admissionFee" integer default 0;
alter table students add column if not exists discount integer default 0;
alter table students add column if not exists documents jsonb default '{}'::jsonb;

create unique index if not exists students_admission_number_unique
on students ("admissionNumber")
where "admissionNumber" is not null and "admissionNumber" <> '';

create unique index if not exists students_birth_registration_unique
on students ("birthRegistrationNumber")
where "birthRegistrationNumber" is not null and "birthRegistrationNumber" <> '';

create table if not exists attendance (
  id integer generated by default as identity primary key,
  "studentId" integer not null references students(id) on delete cascade,
  date text not null,
  status text not null,
  unique ("studentId", date)
);

create table if not exists payments (
  id integer generated by default as identity primary key,
  "studentId" integer not null references students(id) on delete cascade,
  student text not null,
  roll text not null,
  amount integer not null,
  date text not null,
  receipt text not null,
  method text default 'Cash',
  status text default 'Completed'
);

create unique index if not exists payments_receipt_unique on payments (receipt);

create table if not exists income (
  id integer generated by default as identity primary key,
  category text not null,
  amount integer not null,
  date text not null,
  note text default '',
  method text default 'Cash',
  receipt text not null,
  "studentId" integer references students(id) on delete set null,
  status text default 'Completed'
);

create unique index if not exists income_receipt_unique on income (receipt);

create table if not exists expenses (
  id integer generated by default as identity primary key,
  cat text not null,
  amount integer not null,
  date text not null,
  note text default ''
);

create table if not exists hifz_logs (
  id integer generated by default as identity primary key,
  "studentId" integer not null references students(id) on delete cascade,
  date text not null,
  sabaq text default ''
);

-- Exam results. "class"/"roll"/"studentName" are stored as a snapshot at
-- save time (same denormalization pattern as payments.student/payments.roll
-- above) so a result stays correct even if a student later changes class or
-- is edited. "published" gates public visibility: staff can enter and
-- correct marks freely, and results only become visible on the public
-- Result Lookup page once explicitly published.
create table if not exists results (
  id integer generated by default as identity primary key,
  "studentId" integer not null references students(id) on delete cascade,
  "examName" text not null,
  year text not null,
  class text not null,
  roll text not null,
  "studentName" text not null,
  subjects jsonb not null default '[]',
  "totalMarks" integer default 0,
  "obtainedMarks" integer default 0,
  gpa text default '',
  grade text default '',
  published integer default 0,
  "updatedAt" timestamptz default now(),
  unique ("studentId", "examName", year)
);

create index if not exists results_lookup_idx on results (class, roll, "examName", published);

create table if not exists settings (
  key text primary key,
  value text not null
);

create table if not exists users (
  id integer generated by default as identity primary key,
  name text not null,
  role text not null default 'Teacher',
  email text unique,
  "passwordHash" text,
  "isProtected" integer default 0
);

-- Account-level brute-force lockout (task 1.2). Added via ALTER because the
-- CREATE TABLE above is a no-op once the table already exists on deployed DBs.
alter table users add column if not exists "failedLoginAttempts" integer not null default 0;
alter table users add column if not exists "lockedUntil" timestamptz;

create table if not exists password_resets (
  id integer generated by default as identity primary key,
  "userId" integer not null references users(id) on delete cascade,
  token text not null unique,
  "expiresAt" text not null
);

create table if not exists delete_requests (
  id integer generated by default as identity primary key,
  "entityType" text not null,
  "entityId" integer not null,
  label text not null,
  amount integer default 0,
  "requestedBy" integer,
  "requestedByName" text default '',
  status text not null default 'pending',
  "createdAt" text not null,
  "resolvedAt" text,
  "resolvedBy" integer,
  payload text default ''
);

create unique index if not exists delete_requests_pending_unique
on delete_requests ("entityType", "entityId", status)
where status = 'pending';

create table if not exists receipt_counters (
  "key" text primary key,
  value bigint not null default 0
);

-- Offline-first foundation (Phase 0): lets the idempotency middleware
-- (server/src/middleware/idempotency.js) recognize a retried mutation —
-- e.g. a payment or admission submitted while offline, queued client-side,
-- and resent once the connection returns — as the SAME request rather than
-- creating a duplicate. clientRequestId is generated in the browser (see
-- client/src/lib/api.ts) and sent as the X-Client-Request-Id header.
create table if not exists sync_requests (
  "clientRequestId" text primary key,
  route text not null,
  "statusCode" integer not null,
  response jsonb default '{}'::jsonb,
  "createdAt" text not null
);

create table if not exists audit_logs (
  id integer generated by default as identity primary key,
  "action" text not null,
  "actorId" integer,
  "actorName" text default '',
  "actorRole" text default '',
  "entityType" text default '',
  "entityId" integer,
  label text default '',
  details text default '',
  "createdAt" text not null
);

create index if not exists audit_logs_created_at_idx on audit_logs ("createdAt" desc);

create table if not exists backup_restore_events (
  id integer generated by default as identity primary key,
  event text not null,
  status text not null,
  "requestedBy" integer,
  "requestedByName" text default '',
  "backupVersion" integer,
  "backupFormat" text default '',
  report jsonb default '{}'::jsonb,
  error text default '',
  "createdAt" text not null
);

-- Public "ভর্তি" (admission) form submissions from the marketing site.
-- Distinct from `students`: these are unverified inbound inquiries a staff
-- member reviews before a real student record is created.
create table if not exists admissions (
  id integer generated by default as identity primary key,
  "studentName" text not null,
  "studentNameEn" text default '',
  "dateOfBirth" text default '',
  gender text default '',
  "className" text not null,
  "guardianName" text not null,
  "guardianPhone" text not null,
  "presentAddress" text default '',
  "previousInstitution" text default '',
  note text default '',
  status text not null default 'Pending',
  "createdAt" text not null
);

create index if not exists admissions_created_at_idx on admissions ("createdAt" desc);

-- In-app notification center. A row is either targeted at specific roles
-- (targetRoles, e.g. new admission -> ["Admin","Super Admin"]) or at one
-- specific user (targetUserId, e.g. "your delete request was approved").
-- Read state is tracked per-user in notification_reads rather than a single
-- boolean on this table, since the same role-targeted notification can be
-- read by one Admin and still unread for another.
create table if not exists notifications (
  id integer generated by default as identity primary key,
  type text not null,
  title text not null,
  body text default '',
  "entityType" text default '',
  "entityId" integer,
  link text default '',
  "targetRoles" text[] not null default '{}',
  "targetUserId" integer references users(id) on delete cascade,
  "createdAt" text not null
);

create index if not exists notifications_created_at_idx on notifications ("createdAt" desc);

create table if not exists notification_reads (
  "notificationId" integer not null references notifications(id) on delete cascade,
  "userId" integer not null references users(id) on delete cascade,
  "readAt" text not null,
  primary key ("notificationId", "userId")
);
