// scripts/sync-roles.js
//
// Reads server/src/config/roles.js (the single source of truth) and
// writes client/src/lib/roles.generated.ts from it.
//
// Run via `npm run sync:roles` (also runs automatically as the first
// step of `npm run check`). Never hand-edit roles.generated.ts.

const fs = require("fs");
const path = require("path");

const { ROLE_PERMISSIONS, ROUTE_PERMISSION } = require(
  path.join(__dirname, "..", "server", "src", "config", "roles.js")
);

const outPath = path.join(__dirname, "..", "client", "src", "lib", "roles.generated.ts");

const header = `// AUTO-GENERATED by scripts/sync-roles.js — DO NOT EDIT BY HAND.
// Source of truth: server/src/config/roles.js
// Run \`npm run sync:roles\` after changing that file.
`;

const body = `${header}
export const ROLE_PERMISSIONS = ${JSON.stringify(ROLE_PERMISSIONS, null, 2)} as const;

export const ROUTE_PERMISSION = ${JSON.stringify(ROUTE_PERMISSION, null, 2)} as const;
`;

fs.writeFileSync(outPath, body, "utf8");
console.log(`[sync-roles] wrote ${path.relative(process.cwd(), outPath)}`);
