// ============================================================================
// tenantResolve.js  (Part 3 / 6 — Tenant Resolution Middleware)
// ============================================================================
// For each incoming /api request, figures out which institution it belongs
// to (subdomain in production, or an X-Tenant-Code header for local/dev
// testing where wildcard subdomains aren't available), checks a dedicated
// Postgres client out of the pool, points its search_path at that
// institution's tenant_xxx schema, and runs the rest of the request inside
// tenantContext.run() so pg.js (query/get/all/run/withTransaction) picks it
// up automatically — no route file needed to change.
//
// OFF BY DEFAULT: this entire middleware is a no-op unless
// MULTI_TENANT_MODE=true is set. Every existing single-tenant deployment
// (no env var set) behaves exactly as before this part — same as Parts 1
// and 2, this only adds new, inert capability until explicitly turned on.
// ============================================================================

const pg = require("../pg");
const tenantContext = require("../tenantContext");
const registryDb = require("../registryDb");

// Paths that never need a tenant connection: health checks, and the future
// Part 5 super-admin panel (which talks only to registry.* — the control
// plane — never to a tenant_xxx schema).
function isSkippedPath(path) {
  if (path === "/api/health") return true;
  if (path.startsWith("/api/platform")) return true;
  // Public self-signup (Step 2/3) — /api/public/signup creates a brand new
  // tenant_xxx schema (it doesn't belong to one), and /api/public/root-domain
  // is a static config read; neither needs Host-based tenant lookup, which
  // would only ever 404 here. Same reasoning as /api/platform above. NOTE:
  // this is distinct from the pre-existing /api/public/site-content and
  // /api/public/settings routes (mounted directly on `app`, not this
  // router), which DO need per-tenant resolution and are intentionally not
  // matched by this prefix check beyond the literal segment below.
  if (path === "/api/public/signup" || path === "/api/public/root-domain") return true;
  // Google's OAuth redirect URI is one fixed URL, registered once in Google
  // Cloud Console, that always points at this backend's own domain (it's
  // handed to Google, not to the frontend) — it can never carry a tenant's
  // subdomain the way a normal frontend fetch does. Host-based lookup below
  // would 404 here for every tenant. routes/backup.js's /google/callback
  // handler resolves the correct tenant itself instead (via withTenantByCode
  // below), using the institution code embedded in the signed `state` param
  // it received back from Google.
  if (path === "/api/backup/google/callback") return true;
  return false;
}

// Schema names are only ever generated by registryDb.codeToSchemaName() at
// provisioning time ("tenant_" + lowercase letters/digits/underscores), but
// this value still ends up interpolated directly into a SQL statement below
// (search_path can't be a bind parameter), so it's double-checked here
// against that exact shape before use — belt-and-braces against a corrupted
// or hand-edited registry row.
const SAFE_SCHEMA_NAME = /^[a-z][a-z0-9_]*$/;

// Resolves `code` to an institution, checks out a dedicated pg client with
// search_path pointed at its tenant_xxx schema, and runs fn(institution)
// inside tenantContext.run() so every db.*() call made during fn() — however
// deeply nested — transparently targets that institution's schema, exactly
// like the tenantResolve middleware below does for normal Host-routed
// requests. Used directly by routes/backup.js for the one route that can't
// rely on Host-based routing (see isSkippedPath above).
async function withTenantByCode(code, fn) {
  const institution = await registryDb.getInstitutionByCode(code);
  if (!institution) {
    const err = new Error("প্রতিষ্ঠান খুঁজে পাওয়া যায়নি");
    err.status = 404;
    throw err;
  }
  if (!registryDb.isAccessAllowed(institution)) {
    const messages = {
      suspended: "এই অ্যাকাউন্টটি সাসপেন্ড করা হয়েছে। বিস্তারিত জানতে যোগাযোগ করুন।",
      cancelled: "এই অ্যাকাউন্টটি বাতিল করা হয়েছে।",
    };
    const err = new Error(messages[institution.status] || "ট্রায়াল/সাবস্ক্রিপশনের মেয়াদ শেষ হয়ে গেছে।");
    err.status = 403;
    throw err;
  }
  if (!SAFE_SCHEMA_NAME.test(institution.schema_name || "")) {
    throw new Error(`Invalid tenant schema name for institution ${institution.id}`);
  }

  const client = await pg.pool.connect();
  try {
    await client.query(`SET search_path TO "${institution.schema_name}", public`);
    return await tenantContext.run({ client, institution }, () => fn(institution));
  } finally {
    try {
      // Reset before returning to the pool so a later single-tenant/public
      // query picked up by a re-used pooled connection never accidentally
      // runs against a leftover tenant schema.
      await client.query("SET search_path TO public");
    } catch (err) {
      console.error("Failed to reset search_path before releasing tenant client:", err.message);
    } finally {
      client.release();
    }
  }
}

// Shared by both the normal Host-based path and the Cloudflare Worker path
// below — turns a hostname into a tenant label, or null for the apex/www/api.
function hostToTenantLabel(host) {
  const normalized = (host || "").toLowerCase();
  if (!normalized) return null;

  const rootDomain = (process.env.PLATFORM_ROOT_DOMAIN || "").toLowerCase();
  if (rootDomain && normalized === rootDomain) return null; // apex domain: no tenant (marketing page / super-admin login)

  const label = normalized.split(".")[0];
  if (!label || label === "www" || label === "api") return null;
  return label;
}

function extractTenantCode(req) {
  // Cloudflare Worker wildcard-subdomain proxy (see
  // cloudflare-worker/tenant-router.js): the Worker terminates
  // *.{PLATFORM_ROOT_DOMAIN} traffic for free (no GCP load balancer / static
  // IP needed) and forwards requests to this service's default Cloud Run
  // URL. The Fetch API forbids a Worker from overriding the real Host
  // header on that forwarded request, so it sends the browser's original
  // hostname in X-Original-Host instead, alongside a shared secret only the
  // Worker knows. Without a matching secret this header is ignored — so it
  // can't be used to spoof a tenant the way a bare client-supplied header
  // could, which is exactly why X-Tenant-Code below stays disabled in
  // production.
  const workerSecret = process.env.CF_WORKER_SHARED_SECRET;
  if (workerSecret && req.get("x-worker-secret") === workerSecret) {
    const label = hostToTenantLabel(req.get("x-original-host"));
    if (label) return label;
  }

  // Header override: lets local development and any environment without
  // wildcard DNS/subdomains (e.g. testing against localhost:10000) select a
  // tenant explicitly. Only ever changes *which schema* a request reads —
  // it grants no extra privilege on its own, since every route past this
  // middleware still enforces its own auth/RBAC exactly as before (a JWT's
  // institutionCode is checked against the resolved tenant in auth.js).
  // Still, in production the documented model is "Host decides the tenant"
  // — so the header override is disabled there, closing off tenant
  // enumeration / cross-tenant probing on public routes via a spoofed
  // header instead of relying solely on the JWT check downstream.
  if (process.env.NODE_ENV !== "production") {
    const headerCode = req.get("x-tenant-code");
    if (headerCode) return headerCode.trim().toLowerCase();
  }

  return hostToTenantLabel(req.hostname);
}

async function tenantResolve(req, res, next) {
  if (!req.path.startsWith("/api/")) return next();
  if (process.env.MULTI_TENANT_MODE !== "true") return next();
  if (isSkippedPath(req.path)) return next();

  const code = extractTenantCode(req);

  let institution;
  try {
    if (code) {
      institution = await registryDb.getInstitutionByCode(code);
    }
    // Falls through here for two cases: no code at all (host isn't a
    // "label.rootDomain" subdomain — e.g. an institution's own domain like
    // "school.theirdomain.com" or "theirdomain.com"), or a code that came
    // back with no match (typo'd subdomain vs. a real custom domain that
    // happens to have a dot in its first label). Either way, try the Host
    // header as a literal custom_domain before giving up.
    if (!institution) {
      const host = (req.hostname || "").toLowerCase();
      if (host) institution = await registryDb.getInstitutionByDomain(host);
    }
  } catch (err) {
    return next(err);
  }

  if (!institution) {
    if (!code) {
      return res.status(400).json({ error: "প্রতিষ্ঠান শনাক্ত করা যায়নি" });
    }
    return res.status(404).json({ error: "প্রতিষ্ঠান খুঁজে পাওয়া যায়নি" });
  }
  if (!registryDb.isAccessAllowed(institution)) {
    const messages = {
      suspended: "এই অ্যাকাউন্টটি সাসপেন্ড করা হয়েছে। বিস্তারিত জানতে যোগাযোগ করুন।",
      cancelled: "এই অ্যাকাউন্টটি বাতিল করা হয়েছে।",
    };
    return res.status(403).json({
      error: messages[institution.status] || "ট্রায়াল/সাবস্ক্রিপশনের মেয়াদ শেষ হয়ে গেছে।",
    });
  }
  if (!SAFE_SCHEMA_NAME.test(institution.schema_name || "")) {
    return next(new Error(`Invalid tenant schema name for institution ${institution.id}`));
  }

  let client;
  let released = false;
  const releaseClient = async () => {
    if (released || !client) return;
    released = true;
    try {
      // Reset before returning to the pool so a later single-tenant/public
      // query picked up by a re-used pooled connection never accidentally
      // runs against a leftover tenant schema.
      await client.query("SET search_path TO public");
    } catch (err) {
      console.error("Failed to reset search_path before releasing tenant client:", err.message);
    } finally {
      client.release();
    }
  };

  try {
    client = await pg.pool.connect();
    await client.query(`SET search_path TO "${institution.schema_name}", public`);
  } catch (err) {
    if (client) client.release();
    return next(err);
  }

  // Covers both normal completions and premature disconnects (client closed
  // the connection before a response was sent) so the checked-out client is
  // never leaked back to the pool.
  res.on("finish", releaseClient);
  res.on("close", releaseClient);

  req.tenant = institution;

  tenantContext.run({ client, institution }, () => next());
}

module.exports = tenantResolve;
module.exports.withTenantByCode = withTenantByCode;
module.exports.extractTenantCode = extractTenantCode;
