// ============================================================================
// tenantResolve.js  (Part 3 / 6 — Tenant Resolution Middleware)
// ============================================================================
// For each incoming /api request, figures out which institution it belongs
// to (subdomain in production, or an X-Tenant-Code header for local/dev
// testing where wildcard subdomains aren't available), checks a dedicated
// Postgres client out of the pool, points its search_path at that
// institution's tenant_xxx schema, and runs the rest of the request inside
// tenantContext.run() so pg.js (query/get/all/run/withTransaction) picks it
// up automatically — no route file needed to change.
//
// OFF BY DEFAULT: this entire middleware is a no-op unless
// MULTI_TENANT_MODE=true is set. Every existing single-tenant deployment
// (no env var set) behaves exactly as before this part — same as Parts 1
// and 2, this only adds new, inert capability until explicitly turned on.
// ============================================================================

const pg = require("../pg");
const tenantContext = require("../tenantContext");
const registryDb = require("../registryDb");

// Paths that never need a tenant connection: health checks, and the future
// Part 5 super-admin panel (which talks only to registry.* — the control
// plane — never to a tenant_xxx schema).
function isSkippedPath(path) {
  if (path === "/api/health") return true;
  if (path.startsWith("/api/platform")) return true;
  return false;
}

// Schema names are only ever generated by registryDb.codeToSchemaName() at
// provisioning time ("tenant_" + lowercase letters/digits/underscores), but
// this value still ends up interpolated directly into a SQL statement below
// (search_path can't be a bind parameter), so it's double-checked here
// against that exact shape before use — belt-and-braces against a corrupted
// or hand-edited registry row.
const SAFE_SCHEMA_NAME = /^[a-z][a-z0-9_]*$/;

function extractTenantCode(req) {
  // Header override: lets local development and any environment without
  // wildcard DNS/subdomains (e.g. testing against localhost:10000) select a
  // tenant explicitly. Only ever changes *which schema* a request reads —
  // it grants no extra privilege, since every route past this middleware
  // still enforces its own auth/RBAC exactly as before.
  const headerCode = req.get("x-tenant-code");
  if (headerCode) return headerCode.trim().toLowerCase();

  const host = (req.hostname || "").toLowerCase();
  if (!host) return null;

  const rootDomain = (process.env.PLATFORM_ROOT_DOMAIN || "").toLowerCase();
  if (rootDomain && host === rootDomain) return null; // apex domain: no tenant (marketing page / super-admin login)

  const label = host.split(".")[0];
  if (!label || label === "www" || label === "api") return null;
  return label;
}

async function tenantResolve(req, res, next) {
  if (!req.path.startsWith("/api/")) return next();
  if (process.env.MULTI_TENANT_MODE !== "true") return next();
  if (isSkippedPath(req.path)) return next();

  const code = extractTenantCode(req);
  if (!code) {
    return res.status(400).json({ error: "প্রতিষ্ঠান শনাক্ত করা যায়নি" });
  }

  let institution;
  try {
    institution = await registryDb.getInstitutionByCode(code);
  } catch (err) {
    return next(err);
  }

  if (!institution) {
    return res.status(404).json({ error: "প্রতিষ্ঠান খুঁজে পাওয়া যায়নি" });
  }
  if (!registryDb.isAccessAllowed(institution)) {
    const messages = {
      suspended: "এই অ্যাকাউন্টটি সাসপেন্ড করা হয়েছে। বিস্তারিত জানতে যোগাযোগ করুন।",
      cancelled: "এই অ্যাকাউন্টটি বাতিল করা হয়েছে।",
    };
    return res.status(403).json({
      error: messages[institution.status] || "ট্রায়াল/সাবস্ক্রিপশনের মেয়াদ শেষ হয়ে গেছে।",
    });
  }
  if (!SAFE_SCHEMA_NAME.test(institution.schema_name || "")) {
    return next(new Error(`Invalid tenant schema name for institution ${institution.id}`));
  }

  let client;
  let released = false;
  const releaseClient = async () => {
    if (released || !client) return;
    released = true;
    try {
      // Reset before returning to the pool so a later single-tenant/public
      // query picked up by a re-used pooled connection never accidentally
      // runs against a leftover tenant schema.
      await client.query("SET search_path TO public");
    } catch (err) {
      console.error("Failed to reset search_path before releasing tenant client:", err.message);
    } finally {
      client.release();
    }
  };

  try {
    client = await pg.pool.connect();
    await client.query(`SET search_path TO "${institution.schema_name}", public`);
  } catch (err) {
    if (client) client.release();
    return next(err);
  }

  // Covers both normal completions and premature disconnects (client closed
  // the connection before a response was sent) so the checked-out client is
  // never leaked back to the pool.
  res.on("finish", releaseClient);
  res.on("close", releaseClient);

  req.tenant = institution;

  tenantContext.run({ client, institution }, () => next());
}

module.exports = tenantResolve;
